// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// Alias is an object representing the database table.
type Alias struct {
	ID         null.Int64  `boil:"id" json:"id,omitempty" toml:"id" yaml:"id,omitempty"`
	Alias      null.String `boil:"alias" json:"alias,omitempty" toml:"alias" yaml:"alias,omitempty"`
	RealTitle  null.String `boil:"realTitle" json:"realTitle,omitempty" toml:"realTitle" yaml:"realTitle,omitempty"`
	MetaDataId null.Int64  `boil:"metaDataId" json:"metaDataId,omitempty" toml:"metaDataId" yaml:"metaDataId,omitempty"`

	R *aliasR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L aliasL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var AliasColumns = struct {
	ID         string
	Alias      string
	RealTitle  string
	MetaDataId string
}{
	ID:         "id",
	Alias:      "alias",
	RealTitle:  "realTitle",
	MetaDataId: "metaDataId",
}

var AliasTableColumns = struct {
	ID         string
	Alias      string
	RealTitle  string
	MetaDataId string
}{
	ID:         "alias.id",
	Alias:      "alias.alias",
	RealTitle:  "alias.realTitle",
	MetaDataId: "alias.metaDataId",
}

// Generated where

var AliasWhere = struct {
	ID         whereHelpernull_Int64
	Alias      whereHelpernull_String
	RealTitle  whereHelpernull_String
	MetaDataId whereHelpernull_Int64
}{
	ID:         whereHelpernull_Int64{field: "\"alias\".\"id\""},
	Alias:      whereHelpernull_String{field: "\"alias\".\"alias\""},
	RealTitle:  whereHelpernull_String{field: "\"alias\".\"realTitle\""},
	MetaDataId: whereHelpernull_Int64{field: "\"alias\".\"metaDataId\""},
}

// AliasRels is where relationship names are stored.
var AliasRels = struct {
	MetaDataIdMetaDatum string
}{
	MetaDataIdMetaDatum: "MetaDataIdMetaDatum",
}

// aliasR is where relationships are stored.
type aliasR struct {
	MetaDataIdMetaDatum *MetaDatum `boil:"MetaDataIdMetaDatum" json:"MetaDataIdMetaDatum" toml:"MetaDataIdMetaDatum" yaml:"MetaDataIdMetaDatum"`
}

// NewStruct creates a new relationship struct
func (*aliasR) NewStruct() *aliasR {
	return &aliasR{}
}

func (r *aliasR) GetMetaDataIdMetaDatum() *MetaDatum {
	if r == nil {
		return nil
	}
	return r.MetaDataIdMetaDatum
}

// aliasL is where Load methods for each relationship are stored.
type aliasL struct{}

var (
	aliasAllColumns            = []string{"id", "alias", "realTitle", "metaDataId"}
	aliasColumnsWithoutDefault = []string{}
	aliasColumnsWithDefault    = []string{"id", "alias", "realTitle", "metaDataId"}
	aliasPrimaryKeyColumns     = []string{"id"}
	aliasGeneratedColumns      = []string{"id"}
)

type (
	// AliasSlice is an alias for a slice of pointers to Alias.
	// This should almost always be used instead of []Alias.
	AliasSlice []*Alias
	// AliasHook is the signature for custom Alias hook methods
	AliasHook func(context.Context, boil.ContextExecutor, *Alias) error

	aliasQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	aliasType                 = reflect.TypeOf(&Alias{})
	aliasMapping              = queries.MakeStructMapping(aliasType)
	aliasPrimaryKeyMapping, _ = queries.BindMapping(aliasType, aliasMapping, aliasPrimaryKeyColumns)
	aliasInsertCacheMut       sync.RWMutex
	aliasInsertCache          = make(map[string]insertCache)
	aliasUpdateCacheMut       sync.RWMutex
	aliasUpdateCache          = make(map[string]updateCache)
	aliasUpsertCacheMut       sync.RWMutex
	aliasUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var aliasAfterSelectMu sync.Mutex
var aliasAfterSelectHooks []AliasHook

var aliasBeforeInsertMu sync.Mutex
var aliasBeforeInsertHooks []AliasHook
var aliasAfterInsertMu sync.Mutex
var aliasAfterInsertHooks []AliasHook

var aliasBeforeUpdateMu sync.Mutex
var aliasBeforeUpdateHooks []AliasHook
var aliasAfterUpdateMu sync.Mutex
var aliasAfterUpdateHooks []AliasHook

var aliasBeforeDeleteMu sync.Mutex
var aliasBeforeDeleteHooks []AliasHook
var aliasAfterDeleteMu sync.Mutex
var aliasAfterDeleteHooks []AliasHook

var aliasBeforeUpsertMu sync.Mutex
var aliasBeforeUpsertHooks []AliasHook
var aliasAfterUpsertMu sync.Mutex
var aliasAfterUpsertHooks []AliasHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Alias) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range aliasAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Alias) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range aliasBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Alias) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range aliasAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Alias) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range aliasBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Alias) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range aliasAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Alias) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range aliasBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Alias) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range aliasAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Alias) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range aliasBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Alias) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range aliasAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddAliasHook registers your hook function for all future operations.
func AddAliasHook(hookPoint boil.HookPoint, aliasHook AliasHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		aliasAfterSelectMu.Lock()
		aliasAfterSelectHooks = append(aliasAfterSelectHooks, aliasHook)
		aliasAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		aliasBeforeInsertMu.Lock()
		aliasBeforeInsertHooks = append(aliasBeforeInsertHooks, aliasHook)
		aliasBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		aliasAfterInsertMu.Lock()
		aliasAfterInsertHooks = append(aliasAfterInsertHooks, aliasHook)
		aliasAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		aliasBeforeUpdateMu.Lock()
		aliasBeforeUpdateHooks = append(aliasBeforeUpdateHooks, aliasHook)
		aliasBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		aliasAfterUpdateMu.Lock()
		aliasAfterUpdateHooks = append(aliasAfterUpdateHooks, aliasHook)
		aliasAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		aliasBeforeDeleteMu.Lock()
		aliasBeforeDeleteHooks = append(aliasBeforeDeleteHooks, aliasHook)
		aliasBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		aliasAfterDeleteMu.Lock()
		aliasAfterDeleteHooks = append(aliasAfterDeleteHooks, aliasHook)
		aliasAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		aliasBeforeUpsertMu.Lock()
		aliasBeforeUpsertHooks = append(aliasBeforeUpsertHooks, aliasHook)
		aliasBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		aliasAfterUpsertMu.Lock()
		aliasAfterUpsertHooks = append(aliasAfterUpsertHooks, aliasHook)
		aliasAfterUpsertMu.Unlock()
	}
}

// OneG returns a single alias record from the query using the global executor.
func (q aliasQuery) OneG(ctx context.Context) (*Alias, error) {
	return q.One(ctx, boil.GetContextDB())
}

// OneGP returns a single alias record from the query using the global executor, and panics on error.
func (q aliasQuery) OneGP(ctx context.Context) *Alias {
	o, err := q.One(ctx, boil.GetContextDB())
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// OneP returns a single alias record from the query, and panics on error.
func (q aliasQuery) OneP(ctx context.Context, exec boil.ContextExecutor) *Alias {
	o, err := q.One(ctx, exec)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// One returns a single alias record from the query.
func (q aliasQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Alias, error) {
	o := &Alias{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for alias")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// AllG returns all Alias records from the query using the global executor.
func (q aliasQuery) AllG(ctx context.Context) (AliasSlice, error) {
	return q.All(ctx, boil.GetContextDB())
}

// AllGP returns all Alias records from the query using the global executor, and panics on error.
func (q aliasQuery) AllGP(ctx context.Context) AliasSlice {
	o, err := q.All(ctx, boil.GetContextDB())
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// AllP returns all Alias records from the query, and panics on error.
func (q aliasQuery) AllP(ctx context.Context, exec boil.ContextExecutor) AliasSlice {
	o, err := q.All(ctx, exec)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// All returns all Alias records from the query.
func (q aliasQuery) All(ctx context.Context, exec boil.ContextExecutor) (AliasSlice, error) {
	var o []*Alias

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Alias slice")
	}

	if len(aliasAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountG returns the count of all Alias records in the query using the global executor
func (q aliasQuery) CountG(ctx context.Context) (int64, error) {
	return q.Count(ctx, boil.GetContextDB())
}

// CountGP returns the count of all Alias records in the query using the global executor, and panics on error.
func (q aliasQuery) CountGP(ctx context.Context) int64 {
	c, err := q.Count(ctx, boil.GetContextDB())
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return c
}

// CountP returns the count of all Alias records in the query, and panics on error.
func (q aliasQuery) CountP(ctx context.Context, exec boil.ContextExecutor) int64 {
	c, err := q.Count(ctx, exec)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return c
}

// Count returns the count of all Alias records in the query.
func (q aliasQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count alias rows")
	}

	return count, nil
}

// ExistsG checks if the row exists in the table using the global executor.
func (q aliasQuery) ExistsG(ctx context.Context) (bool, error) {
	return q.Exists(ctx, boil.GetContextDB())
}

// ExistsGP checks if the row exists in the table using the global executor, and panics on error.
func (q aliasQuery) ExistsGP(ctx context.Context) bool {
	e, err := q.Exists(ctx, boil.GetContextDB())
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// ExistsP checks if the row exists in the table, and panics on error.
func (q aliasQuery) ExistsP(ctx context.Context, exec boil.ContextExecutor) bool {
	e, err := q.Exists(ctx, exec)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// Exists checks if the row exists in the table.
func (q aliasQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if alias exists")
	}

	return count > 0, nil
}

// MetaDataIdMetaDatum pointed to by the foreign key.
func (o *Alias) MetaDataIdMetaDatum(mods ...qm.QueryMod) metaDatumQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.MetaDataId),
	}

	queryMods = append(queryMods, mods...)

	return MetaData(queryMods...)
}

// LoadMetaDataIdMetaDatum allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (aliasL) LoadMetaDataIdMetaDatum(ctx context.Context, e boil.ContextExecutor, singular bool, maybeAlias interface{}, mods queries.Applicator) error {
	var slice []*Alias
	var object *Alias

	if singular {
		var ok bool
		object, ok = maybeAlias.(*Alias)
		if !ok {
			object = new(Alias)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeAlias)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeAlias))
			}
		}
	} else {
		s, ok := maybeAlias.(*[]*Alias)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeAlias)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeAlias))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &aliasR{}
		}
		if !queries.IsNil(object.MetaDataId) {
			args[object.MetaDataId] = struct{}{}
		}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &aliasR{}
			}

			if !queries.IsNil(obj.MetaDataId) {
				args[obj.MetaDataId] = struct{}{}
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`metaData`),
		qm.WhereIn(`metaData.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load MetaDatum")
	}

	var resultSlice []*MetaDatum
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice MetaDatum")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for metaData")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for metaData")
	}

	if len(metaDatumAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.MetaDataIdMetaDatum = foreign
		if foreign.R == nil {
			foreign.R = &metaDatumR{}
		}
		foreign.R.MetaDataIdAliases = append(foreign.R.MetaDataIdAliases, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.MetaDataId, foreign.ID) {
				local.R.MetaDataIdMetaDatum = foreign
				if foreign.R == nil {
					foreign.R = &metaDatumR{}
				}
				foreign.R.MetaDataIdAliases = append(foreign.R.MetaDataIdAliases, local)
				break
			}
		}
	}

	return nil
}

// SetMetaDataIdMetaDatumG of the alias to the related item.
// Sets o.R.MetaDataIdMetaDatum to related.
// Adds o to related.R.MetaDataIdAliases.
// Uses the global database handle.
func (o *Alias) SetMetaDataIdMetaDatumG(ctx context.Context, insert bool, related *MetaDatum) error {
	return o.SetMetaDataIdMetaDatum(ctx, boil.GetContextDB(), insert, related)
}

// SetMetaDataIdMetaDatumP of the alias to the related item.
// Sets o.R.MetaDataIdMetaDatum to related.
// Adds o to related.R.MetaDataIdAliases.
// Panics on error.
func (o *Alias) SetMetaDataIdMetaDatumP(ctx context.Context, exec boil.ContextExecutor, insert bool, related *MetaDatum) {
	if err := o.SetMetaDataIdMetaDatum(ctx, exec, insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetMetaDataIdMetaDatumGP of the alias to the related item.
// Sets o.R.MetaDataIdMetaDatum to related.
// Adds o to related.R.MetaDataIdAliases.
// Uses the global database handle and panics on error.
func (o *Alias) SetMetaDataIdMetaDatumGP(ctx context.Context, insert bool, related *MetaDatum) {
	if err := o.SetMetaDataIdMetaDatum(ctx, boil.GetContextDB(), insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetMetaDataIdMetaDatum of the alias to the related item.
// Sets o.R.MetaDataIdMetaDatum to related.
// Adds o to related.R.MetaDataIdAliases.
func (o *Alias) SetMetaDataIdMetaDatum(ctx context.Context, exec boil.ContextExecutor, insert bool, related *MetaDatum) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"alias\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 0, []string{"metaDataId"}),
		strmangle.WhereClause("\"", "\"", 0, aliasPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.MetaDataId, related.ID)
	if o.R == nil {
		o.R = &aliasR{
			MetaDataIdMetaDatum: related,
		}
	} else {
		o.R.MetaDataIdMetaDatum = related
	}

	if related.R == nil {
		related.R = &metaDatumR{
			MetaDataIdAliases: AliasSlice{o},
		}
	} else {
		related.R.MetaDataIdAliases = append(related.R.MetaDataIdAliases, o)
	}

	return nil
}

// RemoveMetaDataIdMetaDatumG relationship.
// Sets o.R.MetaDataIdMetaDatum to nil.
// Removes o from all passed in related items' relationships struct.
// Uses the global database handle.
func (o *Alias) RemoveMetaDataIdMetaDatumG(ctx context.Context, related *MetaDatum) error {
	return o.RemoveMetaDataIdMetaDatum(ctx, boil.GetContextDB(), related)
}

// RemoveMetaDataIdMetaDatumP relationship.
// Sets o.R.MetaDataIdMetaDatum to nil.
// Removes o from all passed in related items' relationships struct.
// Panics on error.
func (o *Alias) RemoveMetaDataIdMetaDatumP(ctx context.Context, exec boil.ContextExecutor, related *MetaDatum) {
	if err := o.RemoveMetaDataIdMetaDatum(ctx, exec, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// RemoveMetaDataIdMetaDatumGP relationship.
// Sets o.R.MetaDataIdMetaDatum to nil.
// Removes o from all passed in related items' relationships struct.
// Uses the global database handle and panics on error.
func (o *Alias) RemoveMetaDataIdMetaDatumGP(ctx context.Context, related *MetaDatum) {
	if err := o.RemoveMetaDataIdMetaDatum(ctx, boil.GetContextDB(), related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// RemoveMetaDataIdMetaDatum relationship.
// Sets o.R.MetaDataIdMetaDatum to nil.
// Removes o from all passed in related items' relationships struct.
func (o *Alias) RemoveMetaDataIdMetaDatum(ctx context.Context, exec boil.ContextExecutor, related *MetaDatum) error {
	var err error

	queries.SetScanner(&o.MetaDataId, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("metaDataId")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.MetaDataIdMetaDatum = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.MetaDataIdAliases {
		if queries.Equal(o.MetaDataId, ri.MetaDataId) {
			continue
		}

		ln := len(related.R.MetaDataIdAliases)
		if ln > 1 && i < ln-1 {
			related.R.MetaDataIdAliases[i] = related.R.MetaDataIdAliases[ln-1]
		}
		related.R.MetaDataIdAliases = related.R.MetaDataIdAliases[:ln-1]
		break
	}
	return nil
}

// Aliases retrieves all the records using an executor.
func Aliases(mods ...qm.QueryMod) aliasQuery {
	mods = append(mods, qm.From("\"alias\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"alias\".*"})
	}

	return aliasQuery{q}
}

// FindAliasG retrieves a single record by ID.
func FindAliasG(ctx context.Context, iD null.Int64, selectCols ...string) (*Alias, error) {
	return FindAlias(ctx, boil.GetContextDB(), iD, selectCols...)
}

// FindAliasP retrieves a single record by ID with an executor, and panics on error.
func FindAliasP(ctx context.Context, exec boil.ContextExecutor, iD null.Int64, selectCols ...string) *Alias {
	retobj, err := FindAlias(ctx, exec, iD, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// FindAliasGP retrieves a single record by ID, and panics on error.
func FindAliasGP(ctx context.Context, iD null.Int64, selectCols ...string) *Alias {
	retobj, err := FindAlias(ctx, boil.GetContextDB(), iD, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// FindAlias retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindAlias(ctx context.Context, exec boil.ContextExecutor, iD null.Int64, selectCols ...string) (*Alias, error) {
	aliasObj := &Alias{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"alias\" where \"id\"=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, aliasObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from alias")
	}

	if err = aliasObj.doAfterSelectHooks(ctx, exec); err != nil {
		return aliasObj, err
	}

	return aliasObj, nil
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *Alias) InsertG(ctx context.Context, columns boil.Columns) error {
	return o.Insert(ctx, boil.GetContextDB(), columns)
}

// InsertP a single record using an executor, and panics on error. See Insert
// for whitelist behavior description.
func (o *Alias) InsertP(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) {
	if err := o.Insert(ctx, exec, columns); err != nil {
		panic(boil.WrapErr(err))
	}
}

// InsertGP a single record, and panics on error. See Insert for whitelist
// behavior description.
func (o *Alias) InsertGP(ctx context.Context, columns boil.Columns) {
	if err := o.Insert(ctx, boil.GetContextDB(), columns); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Alias) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no alias provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(aliasColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	aliasInsertCacheMut.RLock()
	cache, cached := aliasInsertCache[key]
	aliasInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			aliasAllColumns,
			aliasColumnsWithDefault,
			aliasColumnsWithoutDefault,
			nzDefaults,
		)
		wl = strmangle.SetComplement(wl, aliasGeneratedColumns)

		cache.valueMapping, err = queries.BindMapping(aliasType, aliasMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(aliasType, aliasMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"alias\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"alias\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into alias")
	}

	if !cached {
		aliasInsertCacheMut.Lock()
		aliasInsertCache[key] = cache
		aliasInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// UpdateG a single Alias record using the global executor.
// See Update for more documentation.
func (o *Alias) UpdateG(ctx context.Context, columns boil.Columns) (int64, error) {
	return o.Update(ctx, boil.GetContextDB(), columns)
}

// UpdateP uses an executor to update the Alias, and panics on error.
// See Update for more documentation.
func (o *Alias) UpdateP(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) int64 {
	rowsAff, err := o.Update(ctx, exec, columns)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// UpdateGP a single Alias record using the global executor. Panics on error.
// See Update for more documentation.
func (o *Alias) UpdateGP(ctx context.Context, columns boil.Columns) int64 {
	rowsAff, err := o.Update(ctx, boil.GetContextDB(), columns)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// Update uses an executor to update the Alias.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Alias) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	aliasUpdateCacheMut.RLock()
	cache, cached := aliasUpdateCache[key]
	aliasUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			aliasAllColumns,
			aliasPrimaryKeyColumns,
		)
		wl = strmangle.SetComplement(wl, aliasGeneratedColumns)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update alias, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"alias\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 0, wl),
			strmangle.WhereClause("\"", "\"", 0, aliasPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(aliasType, aliasMapping, append(wl, aliasPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update alias row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for alias")
	}

	if !cached {
		aliasUpdateCacheMut.Lock()
		aliasUpdateCache[key] = cache
		aliasUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAllP updates all rows with matching column names, and panics on error.
func (q aliasQuery) UpdateAllP(ctx context.Context, exec boil.ContextExecutor, cols M) int64 {
	rowsAff, err := q.UpdateAll(ctx, exec, cols)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// UpdateAllG updates all rows with the specified column values.
func (q aliasQuery) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return q.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAllGP updates all rows with the specified column values, and panics on error.
func (q aliasQuery) UpdateAllGP(ctx context.Context, cols M) int64 {
	rowsAff, err := q.UpdateAll(ctx, boil.GetContextDB(), cols)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// UpdateAll updates all rows with the specified column values.
func (q aliasQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for alias")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for alias")
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (o AliasSlice) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return o.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAllGP updates all rows with the specified column values, and panics on error.
func (o AliasSlice) UpdateAllGP(ctx context.Context, cols M) int64 {
	rowsAff, err := o.UpdateAll(ctx, boil.GetContextDB(), cols)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// UpdateAllP updates all rows with the specified column values, and panics on error.
func (o AliasSlice) UpdateAllP(ctx context.Context, exec boil.ContextExecutor, cols M) int64 {
	rowsAff, err := o.UpdateAll(ctx, exec, cols)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o AliasSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), aliasPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"alias\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, aliasPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in alias slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all alias")
	}
	return rowsAff, nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *Alias) UpsertG(ctx context.Context, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	return o.Upsert(ctx, boil.GetContextDB(), updateOnConflict, conflictColumns, updateColumns, insertColumns)
}

// UpsertGP attempts an insert, and does an update or ignore on conflict. Panics on error.
func (o *Alias) UpsertGP(ctx context.Context, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) {
	if err := o.Upsert(ctx, boil.GetContextDB(), updateOnConflict, conflictColumns, updateColumns, insertColumns); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpsertP attempts an insert using an executor, and does an update or ignore on conflict.
// UpsertP panics on error.
func (o *Alias) UpsertP(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) {
	if err := o.Upsert(ctx, exec, updateOnConflict, conflictColumns, updateColumns, insertColumns); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Alias) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no alias provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(aliasColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	aliasUpsertCacheMut.RLock()
	cache, cached := aliasUpsertCache[key]
	aliasUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			aliasAllColumns,
			aliasColumnsWithDefault,
			aliasColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			aliasAllColumns,
			aliasPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert alias, could not build update column list")
		}

		ret := strmangle.SetComplement(aliasAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(aliasPrimaryKeyColumns))
			copy(conflict, aliasPrimaryKeyColumns)
		}
		cache.query = buildUpsertQuerySQLite(dialect, "\"alias\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(aliasType, aliasMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(aliasType, aliasMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert alias")
	}

	if !cached {
		aliasUpsertCacheMut.Lock()
		aliasUpsertCache[key] = cache
		aliasUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// DeleteG deletes a single Alias record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *Alias) DeleteG(ctx context.Context) (int64, error) {
	return o.Delete(ctx, boil.GetContextDB())
}

// DeleteP deletes a single Alias record with an executor.
// DeleteP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *Alias) DeleteP(ctx context.Context, exec boil.ContextExecutor) int64 {
	rowsAff, err := o.Delete(ctx, exec)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// DeleteGP deletes a single Alias record.
// DeleteGP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *Alias) DeleteGP(ctx context.Context) int64 {
	rowsAff, err := o.Delete(ctx, boil.GetContextDB())
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// Delete deletes a single Alias record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Alias) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no Alias provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), aliasPrimaryKeyMapping)
	sql := "DELETE FROM \"alias\" WHERE \"id\"=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from alias")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for alias")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

func (q aliasQuery) DeleteAllG(ctx context.Context) (int64, error) {
	return q.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAllP deletes all rows, and panics on error.
func (q aliasQuery) DeleteAllP(ctx context.Context, exec boil.ContextExecutor) int64 {
	rowsAff, err := q.DeleteAll(ctx, exec)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// DeleteAllGP deletes all rows, and panics on error.
func (q aliasQuery) DeleteAllGP(ctx context.Context) int64 {
	rowsAff, err := q.DeleteAll(ctx, boil.GetContextDB())
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// DeleteAll deletes all matching rows.
func (q aliasQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no aliasQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from alias")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for alias")
	}

	return rowsAff, nil
}

// DeleteAllG deletes all rows in the slice.
func (o AliasSlice) DeleteAllG(ctx context.Context) (int64, error) {
	return o.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAllP deletes all rows in the slice, using an executor, and panics on error.
func (o AliasSlice) DeleteAllP(ctx context.Context, exec boil.ContextExecutor) int64 {
	rowsAff, err := o.DeleteAll(ctx, exec)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// DeleteAllGP deletes all rows in the slice, and panics on error.
func (o AliasSlice) DeleteAllGP(ctx context.Context) int64 {
	rowsAff, err := o.DeleteAll(ctx, boil.GetContextDB())
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o AliasSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(aliasBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), aliasPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"alias\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, aliasPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from alias slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for alias")
	}

	if len(aliasAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// ReloadG refetches the object from the database using the primary keys.
func (o *Alias) ReloadG(ctx context.Context) error {
	if o == nil {
		return errors.New("models: no Alias provided for reload")
	}

	return o.Reload(ctx, boil.GetContextDB())
}

// ReloadP refetches the object from the database with an executor. Panics on error.
func (o *Alias) ReloadP(ctx context.Context, exec boil.ContextExecutor) {
	if err := o.Reload(ctx, exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadGP refetches the object from the database and panics on error.
func (o *Alias) ReloadGP(ctx context.Context) {
	if err := o.Reload(ctx, boil.GetContextDB()); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Alias) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindAlias(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *AliasSlice) ReloadAllG(ctx context.Context) error {
	if o == nil {
		return errors.New("models: empty AliasSlice provided for reload all")
	}

	return o.ReloadAll(ctx, boil.GetContextDB())
}

// ReloadAllP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *AliasSlice) ReloadAllP(ctx context.Context, exec boil.ContextExecutor) {
	if err := o.ReloadAll(ctx, exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllGP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *AliasSlice) ReloadAllGP(ctx context.Context) {
	if err := o.ReloadAll(ctx, boil.GetContextDB()); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *AliasSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := AliasSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), aliasPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"alias\".* FROM \"alias\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, aliasPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in AliasSlice")
	}

	*o = slice

	return nil
}

// AliasExistsG checks if the Alias row exists.
func AliasExistsG(ctx context.Context, iD null.Int64) (bool, error) {
	return AliasExists(ctx, boil.GetContextDB(), iD)
}

// AliasExistsP checks if the Alias row exists. Panics on error.
func AliasExistsP(ctx context.Context, exec boil.ContextExecutor, iD null.Int64) bool {
	e, err := AliasExists(ctx, exec, iD)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// AliasExistsGP checks if the Alias row exists. Panics on error.
func AliasExistsGP(ctx context.Context, iD null.Int64) bool {
	e, err := AliasExists(ctx, boil.GetContextDB(), iD)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// AliasExists checks if the Alias row exists.
func AliasExists(ctx context.Context, exec boil.ContextExecutor, iD null.Int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"alias\" where \"id\"=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if alias exists")
	}

	return exists, nil
}

// Exists checks if the Alias row exists.
func (o *Alias) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return AliasExists(ctx, exec, o.ID)
}
