// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

// This test suite runs each operation test in parallel.
// Example, if your database has 3 tables, the suite will run:
// table1, table2 and table3 Delete in parallel
// table1, table2 and table3 Insert in parallel, and so forth.
// It does NOT run each operation group in parallel.
// Separating the tests thusly grants avoidance of Postgres deadlocks.
func TestParent(t *testing.T) {
	t.Run("AbsMetaData", testAbsMetaData)
	t.Run("Aliases", testAliases)
	t.Run("Episodes", testEpisodes)
	t.Run("Genres", testGenres)
	t.Run("MediaFiles", testMediaFiles)
	t.Run("MetaData", testMetaData)
	t.Run("TorrentFiles", testTorrentFiles)
	t.Run("Users", testUsers)
	t.Run("UserEpisodes", testUserEpisodes)
	t.Run("UserMetaData", testUserMetaData)
}

func TestDelete(t *testing.T) {
	t.Run("AbsMetaData", testAbsMetaDataDelete)
	t.Run("Aliases", testAliasesDelete)
	t.Run("Episodes", testEpisodesDelete)
	t.Run("Genres", testGenresDelete)
	t.Run("MediaFiles", testMediaFilesDelete)
	t.Run("MetaData", testMetaDataDelete)
	t.Run("TorrentFiles", testTorrentFilesDelete)
	t.Run("Users", testUsersDelete)
	t.Run("UserEpisodes", testUserEpisodesDelete)
	t.Run("UserMetaData", testUserMetaDataDelete)
}

func TestQueryDeleteAll(t *testing.T) {
	t.Run("AbsMetaData", testAbsMetaDataQueryDeleteAll)
	t.Run("Aliases", testAliasesQueryDeleteAll)
	t.Run("Episodes", testEpisodesQueryDeleteAll)
	t.Run("Genres", testGenresQueryDeleteAll)
	t.Run("MediaFiles", testMediaFilesQueryDeleteAll)
	t.Run("MetaData", testMetaDataQueryDeleteAll)
	t.Run("TorrentFiles", testTorrentFilesQueryDeleteAll)
	t.Run("Users", testUsersQueryDeleteAll)
	t.Run("UserEpisodes", testUserEpisodesQueryDeleteAll)
	t.Run("UserMetaData", testUserMetaDataQueryDeleteAll)
}

func TestSliceDeleteAll(t *testing.T) {
	t.Run("AbsMetaData", testAbsMetaDataSliceDeleteAll)
	t.Run("Aliases", testAliasesSliceDeleteAll)
	t.Run("Episodes", testEpisodesSliceDeleteAll)
	t.Run("Genres", testGenresSliceDeleteAll)
	t.Run("MediaFiles", testMediaFilesSliceDeleteAll)
	t.Run("MetaData", testMetaDataSliceDeleteAll)
	t.Run("TorrentFiles", testTorrentFilesSliceDeleteAll)
	t.Run("Users", testUsersSliceDeleteAll)
	t.Run("UserEpisodes", testUserEpisodesSliceDeleteAll)
	t.Run("UserMetaData", testUserMetaDataSliceDeleteAll)
}

func TestExists(t *testing.T) {
	t.Run("AbsMetaData", testAbsMetaDataExists)
	t.Run("Aliases", testAliasesExists)
	t.Run("Episodes", testEpisodesExists)
	t.Run("Genres", testGenresExists)
	t.Run("MediaFiles", testMediaFilesExists)
	t.Run("MetaData", testMetaDataExists)
	t.Run("TorrentFiles", testTorrentFilesExists)
	t.Run("Users", testUsersExists)
	t.Run("UserEpisodes", testUserEpisodesExists)
	t.Run("UserMetaData", testUserMetaDataExists)
}

func TestFind(t *testing.T) {
	t.Run("AbsMetaData", testAbsMetaDataFind)
	t.Run("Aliases", testAliasesFind)
	t.Run("Episodes", testEpisodesFind)
	t.Run("Genres", testGenresFind)
	t.Run("MediaFiles", testMediaFilesFind)
	t.Run("MetaData", testMetaDataFind)
	t.Run("TorrentFiles", testTorrentFilesFind)
	t.Run("Users", testUsersFind)
	t.Run("UserEpisodes", testUserEpisodesFind)
	t.Run("UserMetaData", testUserMetaDataFind)
}

func TestBind(t *testing.T) {
	t.Run("AbsMetaData", testAbsMetaDataBind)
	t.Run("Aliases", testAliasesBind)
	t.Run("Episodes", testEpisodesBind)
	t.Run("Genres", testGenresBind)
	t.Run("MediaFiles", testMediaFilesBind)
	t.Run("MetaData", testMetaDataBind)
	t.Run("TorrentFiles", testTorrentFilesBind)
	t.Run("Users", testUsersBind)
	t.Run("UserEpisodes", testUserEpisodesBind)
	t.Run("UserMetaData", testUserMetaDataBind)
}

func TestOne(t *testing.T) {
	t.Run("AbsMetaData", testAbsMetaDataOne)
	t.Run("Aliases", testAliasesOne)
	t.Run("Episodes", testEpisodesOne)
	t.Run("Genres", testGenresOne)
	t.Run("MediaFiles", testMediaFilesOne)
	t.Run("MetaData", testMetaDataOne)
	t.Run("TorrentFiles", testTorrentFilesOne)
	t.Run("Users", testUsersOne)
	t.Run("UserEpisodes", testUserEpisodesOne)
	t.Run("UserMetaData", testUserMetaDataOne)
}

func TestAll(t *testing.T) {
	t.Run("AbsMetaData", testAbsMetaDataAll)
	t.Run("Aliases", testAliasesAll)
	t.Run("Episodes", testEpisodesAll)
	t.Run("Genres", testGenresAll)
	t.Run("MediaFiles", testMediaFilesAll)
	t.Run("MetaData", testMetaDataAll)
	t.Run("TorrentFiles", testTorrentFilesAll)
	t.Run("Users", testUsersAll)
	t.Run("UserEpisodes", testUserEpisodesAll)
	t.Run("UserMetaData", testUserMetaDataAll)
}

func TestCount(t *testing.T) {
	t.Run("AbsMetaData", testAbsMetaDataCount)
	t.Run("Aliases", testAliasesCount)
	t.Run("Episodes", testEpisodesCount)
	t.Run("Genres", testGenresCount)
	t.Run("MediaFiles", testMediaFilesCount)
	t.Run("MetaData", testMetaDataCount)
	t.Run("TorrentFiles", testTorrentFilesCount)
	t.Run("Users", testUsersCount)
	t.Run("UserEpisodes", testUserEpisodesCount)
	t.Run("UserMetaData", testUserMetaDataCount)
}

func TestHooks(t *testing.T) {
	t.Run("AbsMetaData", testAbsMetaDataHooks)
	t.Run("Aliases", testAliasesHooks)
	t.Run("Episodes", testEpisodesHooks)
	t.Run("Genres", testGenresHooks)
	t.Run("MediaFiles", testMediaFilesHooks)
	t.Run("MetaData", testMetaDataHooks)
	t.Run("TorrentFiles", testTorrentFilesHooks)
	t.Run("Users", testUsersHooks)
	t.Run("UserEpisodes", testUserEpisodesHooks)
	t.Run("UserMetaData", testUserMetaDataHooks)
}

func TestInsert(t *testing.T) {
	t.Run("AbsMetaData", testAbsMetaDataInsert)
	t.Run("AbsMetaData", testAbsMetaDataInsertWhitelist)
	t.Run("Aliases", testAliasesInsert)
	t.Run("Aliases", testAliasesInsertWhitelist)
	t.Run("Episodes", testEpisodesInsert)
	t.Run("Episodes", testEpisodesInsertWhitelist)
	t.Run("Genres", testGenresInsert)
	t.Run("Genres", testGenresInsertWhitelist)
	t.Run("MediaFiles", testMediaFilesInsert)
	t.Run("MediaFiles", testMediaFilesInsertWhitelist)
	t.Run("MetaData", testMetaDataInsert)
	t.Run("MetaData", testMetaDataInsertWhitelist)
	t.Run("TorrentFiles", testTorrentFilesInsert)
	t.Run("TorrentFiles", testTorrentFilesInsertWhitelist)
	t.Run("Users", testUsersInsert)
	t.Run("Users", testUsersInsertWhitelist)
	t.Run("UserEpisodes", testUserEpisodesInsert)
	t.Run("UserEpisodes", testUserEpisodesInsertWhitelist)
	t.Run("UserMetaData", testUserMetaDataInsert)
	t.Run("UserMetaData", testUserMetaDataInsertWhitelist)
}

func TestReload(t *testing.T) {
	t.Run("AbsMetaData", testAbsMetaDataReload)
	t.Run("Aliases", testAliasesReload)
	t.Run("Episodes", testEpisodesReload)
	t.Run("Genres", testGenresReload)
	t.Run("MediaFiles", testMediaFilesReload)
	t.Run("MetaData", testMetaDataReload)
	t.Run("TorrentFiles", testTorrentFilesReload)
	t.Run("Users", testUsersReload)
	t.Run("UserEpisodes", testUserEpisodesReload)
	t.Run("UserMetaData", testUserMetaDataReload)
}

func TestReloadAll(t *testing.T) {
	t.Run("AbsMetaData", testAbsMetaDataReloadAll)
	t.Run("Aliases", testAliasesReloadAll)
	t.Run("Episodes", testEpisodesReloadAll)
	t.Run("Genres", testGenresReloadAll)
	t.Run("MediaFiles", testMediaFilesReloadAll)
	t.Run("MetaData", testMetaDataReloadAll)
	t.Run("TorrentFiles", testTorrentFilesReloadAll)
	t.Run("Users", testUsersReloadAll)
	t.Run("UserEpisodes", testUserEpisodesReloadAll)
	t.Run("UserMetaData", testUserMetaDataReloadAll)
}

func TestSelect(t *testing.T) {
	t.Run("AbsMetaData", testAbsMetaDataSelect)
	t.Run("Aliases", testAliasesSelect)
	t.Run("Episodes", testEpisodesSelect)
	t.Run("Genres", testGenresSelect)
	t.Run("MediaFiles", testMediaFilesSelect)
	t.Run("MetaData", testMetaDataSelect)
	t.Run("TorrentFiles", testTorrentFilesSelect)
	t.Run("Users", testUsersSelect)
	t.Run("UserEpisodes", testUserEpisodesSelect)
	t.Run("UserMetaData", testUserMetaDataSelect)
}

func TestUpdate(t *testing.T) {
	t.Run("AbsMetaData", testAbsMetaDataUpdate)
	t.Run("Aliases", testAliasesUpdate)
	t.Run("Episodes", testEpisodesUpdate)
	t.Run("Genres", testGenresUpdate)
	t.Run("MediaFiles", testMediaFilesUpdate)
	t.Run("MetaData", testMetaDataUpdate)
	t.Run("TorrentFiles", testTorrentFilesUpdate)
	t.Run("Users", testUsersUpdate)
	t.Run("UserEpisodes", testUserEpisodesUpdate)
	t.Run("UserMetaData", testUserMetaDataUpdate)
}

func TestSliceUpdateAll(t *testing.T) {
	t.Run("AbsMetaData", testAbsMetaDataSliceUpdateAll)
	t.Run("Aliases", testAliasesSliceUpdateAll)
	t.Run("Episodes", testEpisodesSliceUpdateAll)
	t.Run("Genres", testGenresSliceUpdateAll)
	t.Run("MediaFiles", testMediaFilesSliceUpdateAll)
	t.Run("MetaData", testMetaDataSliceUpdateAll)
	t.Run("TorrentFiles", testTorrentFilesSliceUpdateAll)
	t.Run("Users", testUsersSliceUpdateAll)
	t.Run("UserEpisodes", testUserEpisodesSliceUpdateAll)
	t.Run("UserMetaData", testUserMetaDataSliceUpdateAll)
}
