// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// MediaFile is an object representing the database table.
type MediaFile struct {
	ID           null.Int64  `boil:"id" json:"id,omitempty" toml:"id" yaml:"id,omitempty"`
	Raw          null.String `boil:"raw" json:"raw,omitempty" toml:"raw" yaml:"raw,omitempty"`
	Path         null.String `boil:"path" json:"path,omitempty" toml:"path" yaml:"path,omitempty"`
	Hash         null.String `boil:"hash" json:"hash,omitempty" toml:"hash" yaml:"hash,omitempty"`
	Size         null.Int64  `boil:"size" json:"size,omitempty" toml:"size" yaml:"size,omitempty"`
	MetaDataId   null.Int64  `boil:"metaDataId" json:"metaDataId,omitempty" toml:"metaDataId" yaml:"metaDataId,omitempty"`
	EpisodeId    null.Int64  `boil:"episodeId" json:"episodeId,omitempty" toml:"episodeId" yaml:"episodeId,omitempty"`
	Year         null.Int64  `boil:"year" json:"year,omitempty" toml:"year" yaml:"year,omitempty"`
	Resolution   null.String `boil:"resolution" json:"resolution,omitempty" toml:"resolution" yaml:"resolution,omitempty"`
	Quality      null.String `boil:"quality" json:"quality,omitempty" toml:"quality" yaml:"quality,omitempty"`
	Codec        null.String `boil:"codec" json:"codec,omitempty" toml:"codec" yaml:"codec,omitempty"`
	Audio        null.String `boil:"audio" json:"audio,omitempty" toml:"audio" yaml:"audio,omitempty"`
	Group        null.String `boil:"group" json:"group,omitempty" toml:"group" yaml:"group,omitempty"`
	Region       null.String `boil:"region" json:"region,omitempty" toml:"region" yaml:"region,omitempty"`
	Language     null.String `boil:"language" json:"language,omitempty" toml:"language" yaml:"language,omitempty"`
	Extended     null.Bool   `boil:"extended" json:"extended,omitempty" toml:"extended" yaml:"extended,omitempty"`
	Hardcoded    null.Bool   `boil:"hardcoded" json:"hardcoded,omitempty" toml:"hardcoded" yaml:"hardcoded,omitempty"`
	Proper       null.Bool   `boil:"proper" json:"proper,omitempty" toml:"proper" yaml:"proper,omitempty"`
	Repack       null.Bool   `boil:"repack" json:"repack,omitempty" toml:"repack" yaml:"repack,omitempty"`
	WideScreen   null.Bool   `boil:"wideScreen" json:"wideScreen,omitempty" toml:"wideScreen" yaml:"wideScreen,omitempty"`
	DownloadedAt null.Time   `boil:"downloadedAt" json:"downloadedAt,omitempty" toml:"downloadedAt" yaml:"downloadedAt,omitempty"`

	R *mediaFileR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L mediaFileL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var MediaFileColumns = struct {
	ID           string
	Raw          string
	Path         string
	Hash         string
	Size         string
	MetaDataId   string
	EpisodeId    string
	Year         string
	Resolution   string
	Quality      string
	Codec        string
	Audio        string
	Group        string
	Region       string
	Language     string
	Extended     string
	Hardcoded    string
	Proper       string
	Repack       string
	WideScreen   string
	DownloadedAt string
}{
	ID:           "id",
	Raw:          "raw",
	Path:         "path",
	Hash:         "hash",
	Size:         "size",
	MetaDataId:   "metaDataId",
	EpisodeId:    "episodeId",
	Year:         "year",
	Resolution:   "resolution",
	Quality:      "quality",
	Codec:        "codec",
	Audio:        "audio",
	Group:        "group",
	Region:       "region",
	Language:     "language",
	Extended:     "extended",
	Hardcoded:    "hardcoded",
	Proper:       "proper",
	Repack:       "repack",
	WideScreen:   "wideScreen",
	DownloadedAt: "downloadedAt",
}

var MediaFileTableColumns = struct {
	ID           string
	Raw          string
	Path         string
	Hash         string
	Size         string
	MetaDataId   string
	EpisodeId    string
	Year         string
	Resolution   string
	Quality      string
	Codec        string
	Audio        string
	Group        string
	Region       string
	Language     string
	Extended     string
	Hardcoded    string
	Proper       string
	Repack       string
	WideScreen   string
	DownloadedAt string
}{
	ID:           "mediaFile.id",
	Raw:          "mediaFile.raw",
	Path:         "mediaFile.path",
	Hash:         "mediaFile.hash",
	Size:         "mediaFile.size",
	MetaDataId:   "mediaFile.metaDataId",
	EpisodeId:    "mediaFile.episodeId",
	Year:         "mediaFile.year",
	Resolution:   "mediaFile.resolution",
	Quality:      "mediaFile.quality",
	Codec:        "mediaFile.codec",
	Audio:        "mediaFile.audio",
	Group:        "mediaFile.group",
	Region:       "mediaFile.region",
	Language:     "mediaFile.language",
	Extended:     "mediaFile.extended",
	Hardcoded:    "mediaFile.hardcoded",
	Proper:       "mediaFile.proper",
	Repack:       "mediaFile.repack",
	WideScreen:   "mediaFile.wideScreen",
	DownloadedAt: "mediaFile.downloadedAt",
}

// Generated where

type whereHelpernull_Time struct{ field string }

func (w whereHelpernull_Time) EQ(x null.Time) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpernull_Time) NEQ(x null.Time) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpernull_Time) LT(x null.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpernull_Time) LTE(x null.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpernull_Time) GT(x null.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpernull_Time) GTE(x null.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

func (w whereHelpernull_Time) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpernull_Time) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }

var MediaFileWhere = struct {
	ID           whereHelpernull_Int64
	Raw          whereHelpernull_String
	Path         whereHelpernull_String
	Hash         whereHelpernull_String
	Size         whereHelpernull_Int64
	MetaDataId   whereHelpernull_Int64
	EpisodeId    whereHelpernull_Int64
	Year         whereHelpernull_Int64
	Resolution   whereHelpernull_String
	Quality      whereHelpernull_String
	Codec        whereHelpernull_String
	Audio        whereHelpernull_String
	Group        whereHelpernull_String
	Region       whereHelpernull_String
	Language     whereHelpernull_String
	Extended     whereHelpernull_Bool
	Hardcoded    whereHelpernull_Bool
	Proper       whereHelpernull_Bool
	Repack       whereHelpernull_Bool
	WideScreen   whereHelpernull_Bool
	DownloadedAt whereHelpernull_Time
}{
	ID:           whereHelpernull_Int64{field: "\"mediaFile\".\"id\""},
	Raw:          whereHelpernull_String{field: "\"mediaFile\".\"raw\""},
	Path:         whereHelpernull_String{field: "\"mediaFile\".\"path\""},
	Hash:         whereHelpernull_String{field: "\"mediaFile\".\"hash\""},
	Size:         whereHelpernull_Int64{field: "\"mediaFile\".\"size\""},
	MetaDataId:   whereHelpernull_Int64{field: "\"mediaFile\".\"metaDataId\""},
	EpisodeId:    whereHelpernull_Int64{field: "\"mediaFile\".\"episodeId\""},
	Year:         whereHelpernull_Int64{field: "\"mediaFile\".\"year\""},
	Resolution:   whereHelpernull_String{field: "\"mediaFile\".\"resolution\""},
	Quality:      whereHelpernull_String{field: "\"mediaFile\".\"quality\""},
	Codec:        whereHelpernull_String{field: "\"mediaFile\".\"codec\""},
	Audio:        whereHelpernull_String{field: "\"mediaFile\".\"audio\""},
	Group:        whereHelpernull_String{field: "\"mediaFile\".\"group\""},
	Region:       whereHelpernull_String{field: "\"mediaFile\".\"region\""},
	Language:     whereHelpernull_String{field: "\"mediaFile\".\"language\""},
	Extended:     whereHelpernull_Bool{field: "\"mediaFile\".\"extended\""},
	Hardcoded:    whereHelpernull_Bool{field: "\"mediaFile\".\"hardcoded\""},
	Proper:       whereHelpernull_Bool{field: "\"mediaFile\".\"proper\""},
	Repack:       whereHelpernull_Bool{field: "\"mediaFile\".\"repack\""},
	WideScreen:   whereHelpernull_Bool{field: "\"mediaFile\".\"wideScreen\""},
	DownloadedAt: whereHelpernull_Time{field: "\"mediaFile\".\"downloadedAt\""},
}

// MediaFileRels is where relationship names are stored.
var MediaFileRels = struct {
	EpisodeIdEpisode    string
	MetaDataIdMetaDatum string
}{
	EpisodeIdEpisode:    "EpisodeIdEpisode",
	MetaDataIdMetaDatum: "MetaDataIdMetaDatum",
}

// mediaFileR is where relationships are stored.
type mediaFileR struct {
	EpisodeIdEpisode    *Episode   `boil:"EpisodeIdEpisode" json:"EpisodeIdEpisode" toml:"EpisodeIdEpisode" yaml:"EpisodeIdEpisode"`
	MetaDataIdMetaDatum *MetaDatum `boil:"MetaDataIdMetaDatum" json:"MetaDataIdMetaDatum" toml:"MetaDataIdMetaDatum" yaml:"MetaDataIdMetaDatum"`
}

// NewStruct creates a new relationship struct
func (*mediaFileR) NewStruct() *mediaFileR {
	return &mediaFileR{}
}

func (r *mediaFileR) GetEpisodeIdEpisode() *Episode {
	if r == nil {
		return nil
	}
	return r.EpisodeIdEpisode
}

func (r *mediaFileR) GetMetaDataIdMetaDatum() *MetaDatum {
	if r == nil {
		return nil
	}
	return r.MetaDataIdMetaDatum
}

// mediaFileL is where Load methods for each relationship are stored.
type mediaFileL struct{}

var (
	mediaFileAllColumns            = []string{"id", "raw", "path", "hash", "size", "metaDataId", "episodeId", "year", "resolution", "quality", "codec", "audio", "group", "region", "language", "extended", "hardcoded", "proper", "repack", "wideScreen", "downloadedAt"}
	mediaFileColumnsWithoutDefault = []string{}
	mediaFileColumnsWithDefault    = []string{"id", "raw", "path", "hash", "size", "metaDataId", "episodeId", "year", "resolution", "quality", "codec", "audio", "group", "region", "language", "extended", "hardcoded", "proper", "repack", "wideScreen", "downloadedAt"}
	mediaFilePrimaryKeyColumns     = []string{"id"}
	mediaFileGeneratedColumns      = []string{"id"}
)

type (
	// MediaFileSlice is an alias for a slice of pointers to MediaFile.
	// This should almost always be used instead of []MediaFile.
	MediaFileSlice []*MediaFile
	// MediaFileHook is the signature for custom MediaFile hook methods
	MediaFileHook func(context.Context, boil.ContextExecutor, *MediaFile) error

	mediaFileQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	mediaFileType                 = reflect.TypeOf(&MediaFile{})
	mediaFileMapping              = queries.MakeStructMapping(mediaFileType)
	mediaFilePrimaryKeyMapping, _ = queries.BindMapping(mediaFileType, mediaFileMapping, mediaFilePrimaryKeyColumns)
	mediaFileInsertCacheMut       sync.RWMutex
	mediaFileInsertCache          = make(map[string]insertCache)
	mediaFileUpdateCacheMut       sync.RWMutex
	mediaFileUpdateCache          = make(map[string]updateCache)
	mediaFileUpsertCacheMut       sync.RWMutex
	mediaFileUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var mediaFileAfterSelectMu sync.Mutex
var mediaFileAfterSelectHooks []MediaFileHook

var mediaFileBeforeInsertMu sync.Mutex
var mediaFileBeforeInsertHooks []MediaFileHook
var mediaFileAfterInsertMu sync.Mutex
var mediaFileAfterInsertHooks []MediaFileHook

var mediaFileBeforeUpdateMu sync.Mutex
var mediaFileBeforeUpdateHooks []MediaFileHook
var mediaFileAfterUpdateMu sync.Mutex
var mediaFileAfterUpdateHooks []MediaFileHook

var mediaFileBeforeDeleteMu sync.Mutex
var mediaFileBeforeDeleteHooks []MediaFileHook
var mediaFileAfterDeleteMu sync.Mutex
var mediaFileAfterDeleteHooks []MediaFileHook

var mediaFileBeforeUpsertMu sync.Mutex
var mediaFileBeforeUpsertHooks []MediaFileHook
var mediaFileAfterUpsertMu sync.Mutex
var mediaFileAfterUpsertHooks []MediaFileHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *MediaFile) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range mediaFileAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *MediaFile) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range mediaFileBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *MediaFile) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range mediaFileAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *MediaFile) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range mediaFileBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *MediaFile) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range mediaFileAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *MediaFile) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range mediaFileBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *MediaFile) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range mediaFileAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *MediaFile) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range mediaFileBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *MediaFile) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range mediaFileAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddMediaFileHook registers your hook function for all future operations.
func AddMediaFileHook(hookPoint boil.HookPoint, mediaFileHook MediaFileHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		mediaFileAfterSelectMu.Lock()
		mediaFileAfterSelectHooks = append(mediaFileAfterSelectHooks, mediaFileHook)
		mediaFileAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		mediaFileBeforeInsertMu.Lock()
		mediaFileBeforeInsertHooks = append(mediaFileBeforeInsertHooks, mediaFileHook)
		mediaFileBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		mediaFileAfterInsertMu.Lock()
		mediaFileAfterInsertHooks = append(mediaFileAfterInsertHooks, mediaFileHook)
		mediaFileAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		mediaFileBeforeUpdateMu.Lock()
		mediaFileBeforeUpdateHooks = append(mediaFileBeforeUpdateHooks, mediaFileHook)
		mediaFileBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		mediaFileAfterUpdateMu.Lock()
		mediaFileAfterUpdateHooks = append(mediaFileAfterUpdateHooks, mediaFileHook)
		mediaFileAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		mediaFileBeforeDeleteMu.Lock()
		mediaFileBeforeDeleteHooks = append(mediaFileBeforeDeleteHooks, mediaFileHook)
		mediaFileBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		mediaFileAfterDeleteMu.Lock()
		mediaFileAfterDeleteHooks = append(mediaFileAfterDeleteHooks, mediaFileHook)
		mediaFileAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		mediaFileBeforeUpsertMu.Lock()
		mediaFileBeforeUpsertHooks = append(mediaFileBeforeUpsertHooks, mediaFileHook)
		mediaFileBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		mediaFileAfterUpsertMu.Lock()
		mediaFileAfterUpsertHooks = append(mediaFileAfterUpsertHooks, mediaFileHook)
		mediaFileAfterUpsertMu.Unlock()
	}
}

// OneG returns a single mediaFile record from the query using the global executor.
func (q mediaFileQuery) OneG(ctx context.Context) (*MediaFile, error) {
	return q.One(ctx, boil.GetContextDB())
}

// OneGP returns a single mediaFile record from the query using the global executor, and panics on error.
func (q mediaFileQuery) OneGP(ctx context.Context) *MediaFile {
	o, err := q.One(ctx, boil.GetContextDB())
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// OneP returns a single mediaFile record from the query, and panics on error.
func (q mediaFileQuery) OneP(ctx context.Context, exec boil.ContextExecutor) *MediaFile {
	o, err := q.One(ctx, exec)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// One returns a single mediaFile record from the query.
func (q mediaFileQuery) One(ctx context.Context, exec boil.ContextExecutor) (*MediaFile, error) {
	o := &MediaFile{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for mediaFile")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// AllG returns all MediaFile records from the query using the global executor.
func (q mediaFileQuery) AllG(ctx context.Context) (MediaFileSlice, error) {
	return q.All(ctx, boil.GetContextDB())
}

// AllGP returns all MediaFile records from the query using the global executor, and panics on error.
func (q mediaFileQuery) AllGP(ctx context.Context) MediaFileSlice {
	o, err := q.All(ctx, boil.GetContextDB())
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// AllP returns all MediaFile records from the query, and panics on error.
func (q mediaFileQuery) AllP(ctx context.Context, exec boil.ContextExecutor) MediaFileSlice {
	o, err := q.All(ctx, exec)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// All returns all MediaFile records from the query.
func (q mediaFileQuery) All(ctx context.Context, exec boil.ContextExecutor) (MediaFileSlice, error) {
	var o []*MediaFile

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to MediaFile slice")
	}

	if len(mediaFileAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountG returns the count of all MediaFile records in the query using the global executor
func (q mediaFileQuery) CountG(ctx context.Context) (int64, error) {
	return q.Count(ctx, boil.GetContextDB())
}

// CountGP returns the count of all MediaFile records in the query using the global executor, and panics on error.
func (q mediaFileQuery) CountGP(ctx context.Context) int64 {
	c, err := q.Count(ctx, boil.GetContextDB())
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return c
}

// CountP returns the count of all MediaFile records in the query, and panics on error.
func (q mediaFileQuery) CountP(ctx context.Context, exec boil.ContextExecutor) int64 {
	c, err := q.Count(ctx, exec)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return c
}

// Count returns the count of all MediaFile records in the query.
func (q mediaFileQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count mediaFile rows")
	}

	return count, nil
}

// ExistsG checks if the row exists in the table using the global executor.
func (q mediaFileQuery) ExistsG(ctx context.Context) (bool, error) {
	return q.Exists(ctx, boil.GetContextDB())
}

// ExistsGP checks if the row exists in the table using the global executor, and panics on error.
func (q mediaFileQuery) ExistsGP(ctx context.Context) bool {
	e, err := q.Exists(ctx, boil.GetContextDB())
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// ExistsP checks if the row exists in the table, and panics on error.
func (q mediaFileQuery) ExistsP(ctx context.Context, exec boil.ContextExecutor) bool {
	e, err := q.Exists(ctx, exec)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// Exists checks if the row exists in the table.
func (q mediaFileQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if mediaFile exists")
	}

	return count > 0, nil
}

// EpisodeIdEpisode pointed to by the foreign key.
func (o *MediaFile) EpisodeIdEpisode(mods ...qm.QueryMod) episodeQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.EpisodeId),
	}

	queryMods = append(queryMods, mods...)

	return Episodes(queryMods...)
}

// MetaDataIdMetaDatum pointed to by the foreign key.
func (o *MediaFile) MetaDataIdMetaDatum(mods ...qm.QueryMod) metaDatumQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.MetaDataId),
	}

	queryMods = append(queryMods, mods...)

	return MetaData(queryMods...)
}

// LoadEpisodeIdEpisode allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (mediaFileL) LoadEpisodeIdEpisode(ctx context.Context, e boil.ContextExecutor, singular bool, maybeMediaFile interface{}, mods queries.Applicator) error {
	var slice []*MediaFile
	var object *MediaFile

	if singular {
		var ok bool
		object, ok = maybeMediaFile.(*MediaFile)
		if !ok {
			object = new(MediaFile)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeMediaFile)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeMediaFile))
			}
		}
	} else {
		s, ok := maybeMediaFile.(*[]*MediaFile)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeMediaFile)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeMediaFile))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &mediaFileR{}
		}
		if !queries.IsNil(object.EpisodeId) {
			args[object.EpisodeId] = struct{}{}
		}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &mediaFileR{}
			}

			if !queries.IsNil(obj.EpisodeId) {
				args[obj.EpisodeId] = struct{}{}
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`episode`),
		qm.WhereIn(`episode.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Episode")
	}

	var resultSlice []*Episode
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Episode")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for episode")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for episode")
	}

	if len(episodeAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.EpisodeIdEpisode = foreign
		if foreign.R == nil {
			foreign.R = &episodeR{}
		}
		foreign.R.EpisodeIdMediaFiles = append(foreign.R.EpisodeIdMediaFiles, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.EpisodeId, foreign.ID) {
				local.R.EpisodeIdEpisode = foreign
				if foreign.R == nil {
					foreign.R = &episodeR{}
				}
				foreign.R.EpisodeIdMediaFiles = append(foreign.R.EpisodeIdMediaFiles, local)
				break
			}
		}
	}

	return nil
}

// LoadMetaDataIdMetaDatum allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (mediaFileL) LoadMetaDataIdMetaDatum(ctx context.Context, e boil.ContextExecutor, singular bool, maybeMediaFile interface{}, mods queries.Applicator) error {
	var slice []*MediaFile
	var object *MediaFile

	if singular {
		var ok bool
		object, ok = maybeMediaFile.(*MediaFile)
		if !ok {
			object = new(MediaFile)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeMediaFile)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeMediaFile))
			}
		}
	} else {
		s, ok := maybeMediaFile.(*[]*MediaFile)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeMediaFile)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeMediaFile))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &mediaFileR{}
		}
		if !queries.IsNil(object.MetaDataId) {
			args[object.MetaDataId] = struct{}{}
		}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &mediaFileR{}
			}

			if !queries.IsNil(obj.MetaDataId) {
				args[obj.MetaDataId] = struct{}{}
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`metaData`),
		qm.WhereIn(`metaData.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load MetaDatum")
	}

	var resultSlice []*MetaDatum
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice MetaDatum")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for metaData")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for metaData")
	}

	if len(metaDatumAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.MetaDataIdMetaDatum = foreign
		if foreign.R == nil {
			foreign.R = &metaDatumR{}
		}
		foreign.R.MetaDataIdMediaFiles = append(foreign.R.MetaDataIdMediaFiles, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.MetaDataId, foreign.ID) {
				local.R.MetaDataIdMetaDatum = foreign
				if foreign.R == nil {
					foreign.R = &metaDatumR{}
				}
				foreign.R.MetaDataIdMediaFiles = append(foreign.R.MetaDataIdMediaFiles, local)
				break
			}
		}
	}

	return nil
}

// SetEpisodeIdEpisodeG of the mediaFile to the related item.
// Sets o.R.EpisodeIdEpisode to related.
// Adds o to related.R.EpisodeIdMediaFiles.
// Uses the global database handle.
func (o *MediaFile) SetEpisodeIdEpisodeG(ctx context.Context, insert bool, related *Episode) error {
	return o.SetEpisodeIdEpisode(ctx, boil.GetContextDB(), insert, related)
}

// SetEpisodeIdEpisodeP of the mediaFile to the related item.
// Sets o.R.EpisodeIdEpisode to related.
// Adds o to related.R.EpisodeIdMediaFiles.
// Panics on error.
func (o *MediaFile) SetEpisodeIdEpisodeP(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Episode) {
	if err := o.SetEpisodeIdEpisode(ctx, exec, insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetEpisodeIdEpisodeGP of the mediaFile to the related item.
// Sets o.R.EpisodeIdEpisode to related.
// Adds o to related.R.EpisodeIdMediaFiles.
// Uses the global database handle and panics on error.
func (o *MediaFile) SetEpisodeIdEpisodeGP(ctx context.Context, insert bool, related *Episode) {
	if err := o.SetEpisodeIdEpisode(ctx, boil.GetContextDB(), insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetEpisodeIdEpisode of the mediaFile to the related item.
// Sets o.R.EpisodeIdEpisode to related.
// Adds o to related.R.EpisodeIdMediaFiles.
func (o *MediaFile) SetEpisodeIdEpisode(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Episode) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"mediaFile\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 0, []string{"episodeId"}),
		strmangle.WhereClause("\"", "\"", 0, mediaFilePrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.EpisodeId, related.ID)
	if o.R == nil {
		o.R = &mediaFileR{
			EpisodeIdEpisode: related,
		}
	} else {
		o.R.EpisodeIdEpisode = related
	}

	if related.R == nil {
		related.R = &episodeR{
			EpisodeIdMediaFiles: MediaFileSlice{o},
		}
	} else {
		related.R.EpisodeIdMediaFiles = append(related.R.EpisodeIdMediaFiles, o)
	}

	return nil
}

// RemoveEpisodeIdEpisodeG relationship.
// Sets o.R.EpisodeIdEpisode to nil.
// Removes o from all passed in related items' relationships struct.
// Uses the global database handle.
func (o *MediaFile) RemoveEpisodeIdEpisodeG(ctx context.Context, related *Episode) error {
	return o.RemoveEpisodeIdEpisode(ctx, boil.GetContextDB(), related)
}

// RemoveEpisodeIdEpisodeP relationship.
// Sets o.R.EpisodeIdEpisode to nil.
// Removes o from all passed in related items' relationships struct.
// Panics on error.
func (o *MediaFile) RemoveEpisodeIdEpisodeP(ctx context.Context, exec boil.ContextExecutor, related *Episode) {
	if err := o.RemoveEpisodeIdEpisode(ctx, exec, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// RemoveEpisodeIdEpisodeGP relationship.
// Sets o.R.EpisodeIdEpisode to nil.
// Removes o from all passed in related items' relationships struct.
// Uses the global database handle and panics on error.
func (o *MediaFile) RemoveEpisodeIdEpisodeGP(ctx context.Context, related *Episode) {
	if err := o.RemoveEpisodeIdEpisode(ctx, boil.GetContextDB(), related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// RemoveEpisodeIdEpisode relationship.
// Sets o.R.EpisodeIdEpisode to nil.
// Removes o from all passed in related items' relationships struct.
func (o *MediaFile) RemoveEpisodeIdEpisode(ctx context.Context, exec boil.ContextExecutor, related *Episode) error {
	var err error

	queries.SetScanner(&o.EpisodeId, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("episodeId")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.EpisodeIdEpisode = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.EpisodeIdMediaFiles {
		if queries.Equal(o.EpisodeId, ri.EpisodeId) {
			continue
		}

		ln := len(related.R.EpisodeIdMediaFiles)
		if ln > 1 && i < ln-1 {
			related.R.EpisodeIdMediaFiles[i] = related.R.EpisodeIdMediaFiles[ln-1]
		}
		related.R.EpisodeIdMediaFiles = related.R.EpisodeIdMediaFiles[:ln-1]
		break
	}
	return nil
}

// SetMetaDataIdMetaDatumG of the mediaFile to the related item.
// Sets o.R.MetaDataIdMetaDatum to related.
// Adds o to related.R.MetaDataIdMediaFiles.
// Uses the global database handle.
func (o *MediaFile) SetMetaDataIdMetaDatumG(ctx context.Context, insert bool, related *MetaDatum) error {
	return o.SetMetaDataIdMetaDatum(ctx, boil.GetContextDB(), insert, related)
}

// SetMetaDataIdMetaDatumP of the mediaFile to the related item.
// Sets o.R.MetaDataIdMetaDatum to related.
// Adds o to related.R.MetaDataIdMediaFiles.
// Panics on error.
func (o *MediaFile) SetMetaDataIdMetaDatumP(ctx context.Context, exec boil.ContextExecutor, insert bool, related *MetaDatum) {
	if err := o.SetMetaDataIdMetaDatum(ctx, exec, insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetMetaDataIdMetaDatumGP of the mediaFile to the related item.
// Sets o.R.MetaDataIdMetaDatum to related.
// Adds o to related.R.MetaDataIdMediaFiles.
// Uses the global database handle and panics on error.
func (o *MediaFile) SetMetaDataIdMetaDatumGP(ctx context.Context, insert bool, related *MetaDatum) {
	if err := o.SetMetaDataIdMetaDatum(ctx, boil.GetContextDB(), insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetMetaDataIdMetaDatum of the mediaFile to the related item.
// Sets o.R.MetaDataIdMetaDatum to related.
// Adds o to related.R.MetaDataIdMediaFiles.
func (o *MediaFile) SetMetaDataIdMetaDatum(ctx context.Context, exec boil.ContextExecutor, insert bool, related *MetaDatum) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"mediaFile\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 0, []string{"metaDataId"}),
		strmangle.WhereClause("\"", "\"", 0, mediaFilePrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.MetaDataId, related.ID)
	if o.R == nil {
		o.R = &mediaFileR{
			MetaDataIdMetaDatum: related,
		}
	} else {
		o.R.MetaDataIdMetaDatum = related
	}

	if related.R == nil {
		related.R = &metaDatumR{
			MetaDataIdMediaFiles: MediaFileSlice{o},
		}
	} else {
		related.R.MetaDataIdMediaFiles = append(related.R.MetaDataIdMediaFiles, o)
	}

	return nil
}

// RemoveMetaDataIdMetaDatumG relationship.
// Sets o.R.MetaDataIdMetaDatum to nil.
// Removes o from all passed in related items' relationships struct.
// Uses the global database handle.
func (o *MediaFile) RemoveMetaDataIdMetaDatumG(ctx context.Context, related *MetaDatum) error {
	return o.RemoveMetaDataIdMetaDatum(ctx, boil.GetContextDB(), related)
}

// RemoveMetaDataIdMetaDatumP relationship.
// Sets o.R.MetaDataIdMetaDatum to nil.
// Removes o from all passed in related items' relationships struct.
// Panics on error.
func (o *MediaFile) RemoveMetaDataIdMetaDatumP(ctx context.Context, exec boil.ContextExecutor, related *MetaDatum) {
	if err := o.RemoveMetaDataIdMetaDatum(ctx, exec, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// RemoveMetaDataIdMetaDatumGP relationship.
// Sets o.R.MetaDataIdMetaDatum to nil.
// Removes o from all passed in related items' relationships struct.
// Uses the global database handle and panics on error.
func (o *MediaFile) RemoveMetaDataIdMetaDatumGP(ctx context.Context, related *MetaDatum) {
	if err := o.RemoveMetaDataIdMetaDatum(ctx, boil.GetContextDB(), related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// RemoveMetaDataIdMetaDatum relationship.
// Sets o.R.MetaDataIdMetaDatum to nil.
// Removes o from all passed in related items' relationships struct.
func (o *MediaFile) RemoveMetaDataIdMetaDatum(ctx context.Context, exec boil.ContextExecutor, related *MetaDatum) error {
	var err error

	queries.SetScanner(&o.MetaDataId, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("metaDataId")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.MetaDataIdMetaDatum = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.MetaDataIdMediaFiles {
		if queries.Equal(o.MetaDataId, ri.MetaDataId) {
			continue
		}

		ln := len(related.R.MetaDataIdMediaFiles)
		if ln > 1 && i < ln-1 {
			related.R.MetaDataIdMediaFiles[i] = related.R.MetaDataIdMediaFiles[ln-1]
		}
		related.R.MetaDataIdMediaFiles = related.R.MetaDataIdMediaFiles[:ln-1]
		break
	}
	return nil
}

// MediaFiles retrieves all the records using an executor.
func MediaFiles(mods ...qm.QueryMod) mediaFileQuery {
	mods = append(mods, qm.From("\"mediaFile\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"mediaFile\".*"})
	}

	return mediaFileQuery{q}
}

// FindMediaFileG retrieves a single record by ID.
func FindMediaFileG(ctx context.Context, iD null.Int64, selectCols ...string) (*MediaFile, error) {
	return FindMediaFile(ctx, boil.GetContextDB(), iD, selectCols...)
}

// FindMediaFileP retrieves a single record by ID with an executor, and panics on error.
func FindMediaFileP(ctx context.Context, exec boil.ContextExecutor, iD null.Int64, selectCols ...string) *MediaFile {
	retobj, err := FindMediaFile(ctx, exec, iD, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// FindMediaFileGP retrieves a single record by ID, and panics on error.
func FindMediaFileGP(ctx context.Context, iD null.Int64, selectCols ...string) *MediaFile {
	retobj, err := FindMediaFile(ctx, boil.GetContextDB(), iD, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// FindMediaFile retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindMediaFile(ctx context.Context, exec boil.ContextExecutor, iD null.Int64, selectCols ...string) (*MediaFile, error) {
	mediaFileObj := &MediaFile{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"mediaFile\" where \"id\"=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, mediaFileObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from mediaFile")
	}

	if err = mediaFileObj.doAfterSelectHooks(ctx, exec); err != nil {
		return mediaFileObj, err
	}

	return mediaFileObj, nil
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *MediaFile) InsertG(ctx context.Context, columns boil.Columns) error {
	return o.Insert(ctx, boil.GetContextDB(), columns)
}

// InsertP a single record using an executor, and panics on error. See Insert
// for whitelist behavior description.
func (o *MediaFile) InsertP(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) {
	if err := o.Insert(ctx, exec, columns); err != nil {
		panic(boil.WrapErr(err))
	}
}

// InsertGP a single record, and panics on error. See Insert for whitelist
// behavior description.
func (o *MediaFile) InsertGP(ctx context.Context, columns boil.Columns) {
	if err := o.Insert(ctx, boil.GetContextDB(), columns); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *MediaFile) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no mediaFile provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(mediaFileColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	mediaFileInsertCacheMut.RLock()
	cache, cached := mediaFileInsertCache[key]
	mediaFileInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			mediaFileAllColumns,
			mediaFileColumnsWithDefault,
			mediaFileColumnsWithoutDefault,
			nzDefaults,
		)
		wl = strmangle.SetComplement(wl, mediaFileGeneratedColumns)

		cache.valueMapping, err = queries.BindMapping(mediaFileType, mediaFileMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(mediaFileType, mediaFileMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"mediaFile\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"mediaFile\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into mediaFile")
	}

	if !cached {
		mediaFileInsertCacheMut.Lock()
		mediaFileInsertCache[key] = cache
		mediaFileInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// UpdateG a single MediaFile record using the global executor.
// See Update for more documentation.
func (o *MediaFile) UpdateG(ctx context.Context, columns boil.Columns) (int64, error) {
	return o.Update(ctx, boil.GetContextDB(), columns)
}

// UpdateP uses an executor to update the MediaFile, and panics on error.
// See Update for more documentation.
func (o *MediaFile) UpdateP(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) int64 {
	rowsAff, err := o.Update(ctx, exec, columns)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// UpdateGP a single MediaFile record using the global executor. Panics on error.
// See Update for more documentation.
func (o *MediaFile) UpdateGP(ctx context.Context, columns boil.Columns) int64 {
	rowsAff, err := o.Update(ctx, boil.GetContextDB(), columns)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// Update uses an executor to update the MediaFile.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *MediaFile) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	mediaFileUpdateCacheMut.RLock()
	cache, cached := mediaFileUpdateCache[key]
	mediaFileUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			mediaFileAllColumns,
			mediaFilePrimaryKeyColumns,
		)
		wl = strmangle.SetComplement(wl, mediaFileGeneratedColumns)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update mediaFile, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"mediaFile\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 0, wl),
			strmangle.WhereClause("\"", "\"", 0, mediaFilePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(mediaFileType, mediaFileMapping, append(wl, mediaFilePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update mediaFile row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for mediaFile")
	}

	if !cached {
		mediaFileUpdateCacheMut.Lock()
		mediaFileUpdateCache[key] = cache
		mediaFileUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAllP updates all rows with matching column names, and panics on error.
func (q mediaFileQuery) UpdateAllP(ctx context.Context, exec boil.ContextExecutor, cols M) int64 {
	rowsAff, err := q.UpdateAll(ctx, exec, cols)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// UpdateAllG updates all rows with the specified column values.
func (q mediaFileQuery) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return q.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAllGP updates all rows with the specified column values, and panics on error.
func (q mediaFileQuery) UpdateAllGP(ctx context.Context, cols M) int64 {
	rowsAff, err := q.UpdateAll(ctx, boil.GetContextDB(), cols)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// UpdateAll updates all rows with the specified column values.
func (q mediaFileQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for mediaFile")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for mediaFile")
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (o MediaFileSlice) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return o.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAllGP updates all rows with the specified column values, and panics on error.
func (o MediaFileSlice) UpdateAllGP(ctx context.Context, cols M) int64 {
	rowsAff, err := o.UpdateAll(ctx, boil.GetContextDB(), cols)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// UpdateAllP updates all rows with the specified column values, and panics on error.
func (o MediaFileSlice) UpdateAllP(ctx context.Context, exec boil.ContextExecutor, cols M) int64 {
	rowsAff, err := o.UpdateAll(ctx, exec, cols)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o MediaFileSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), mediaFilePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"mediaFile\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, mediaFilePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in mediaFile slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all mediaFile")
	}
	return rowsAff, nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *MediaFile) UpsertG(ctx context.Context, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	return o.Upsert(ctx, boil.GetContextDB(), updateOnConflict, conflictColumns, updateColumns, insertColumns)
}

// UpsertGP attempts an insert, and does an update or ignore on conflict. Panics on error.
func (o *MediaFile) UpsertGP(ctx context.Context, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) {
	if err := o.Upsert(ctx, boil.GetContextDB(), updateOnConflict, conflictColumns, updateColumns, insertColumns); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpsertP attempts an insert using an executor, and does an update or ignore on conflict.
// UpsertP panics on error.
func (o *MediaFile) UpsertP(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) {
	if err := o.Upsert(ctx, exec, updateOnConflict, conflictColumns, updateColumns, insertColumns); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *MediaFile) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no mediaFile provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(mediaFileColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	mediaFileUpsertCacheMut.RLock()
	cache, cached := mediaFileUpsertCache[key]
	mediaFileUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			mediaFileAllColumns,
			mediaFileColumnsWithDefault,
			mediaFileColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			mediaFileAllColumns,
			mediaFilePrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert mediaFile, could not build update column list")
		}

		ret := strmangle.SetComplement(mediaFileAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(mediaFilePrimaryKeyColumns))
			copy(conflict, mediaFilePrimaryKeyColumns)
		}
		cache.query = buildUpsertQuerySQLite(dialect, "\"mediaFile\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(mediaFileType, mediaFileMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(mediaFileType, mediaFileMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert mediaFile")
	}

	if !cached {
		mediaFileUpsertCacheMut.Lock()
		mediaFileUpsertCache[key] = cache
		mediaFileUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// DeleteG deletes a single MediaFile record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *MediaFile) DeleteG(ctx context.Context) (int64, error) {
	return o.Delete(ctx, boil.GetContextDB())
}

// DeleteP deletes a single MediaFile record with an executor.
// DeleteP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *MediaFile) DeleteP(ctx context.Context, exec boil.ContextExecutor) int64 {
	rowsAff, err := o.Delete(ctx, exec)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// DeleteGP deletes a single MediaFile record.
// DeleteGP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *MediaFile) DeleteGP(ctx context.Context) int64 {
	rowsAff, err := o.Delete(ctx, boil.GetContextDB())
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// Delete deletes a single MediaFile record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *MediaFile) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no MediaFile provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), mediaFilePrimaryKeyMapping)
	sql := "DELETE FROM \"mediaFile\" WHERE \"id\"=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from mediaFile")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for mediaFile")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

func (q mediaFileQuery) DeleteAllG(ctx context.Context) (int64, error) {
	return q.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAllP deletes all rows, and panics on error.
func (q mediaFileQuery) DeleteAllP(ctx context.Context, exec boil.ContextExecutor) int64 {
	rowsAff, err := q.DeleteAll(ctx, exec)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// DeleteAllGP deletes all rows, and panics on error.
func (q mediaFileQuery) DeleteAllGP(ctx context.Context) int64 {
	rowsAff, err := q.DeleteAll(ctx, boil.GetContextDB())
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// DeleteAll deletes all matching rows.
func (q mediaFileQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no mediaFileQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from mediaFile")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for mediaFile")
	}

	return rowsAff, nil
}

// DeleteAllG deletes all rows in the slice.
func (o MediaFileSlice) DeleteAllG(ctx context.Context) (int64, error) {
	return o.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAllP deletes all rows in the slice, using an executor, and panics on error.
func (o MediaFileSlice) DeleteAllP(ctx context.Context, exec boil.ContextExecutor) int64 {
	rowsAff, err := o.DeleteAll(ctx, exec)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// DeleteAllGP deletes all rows in the slice, and panics on error.
func (o MediaFileSlice) DeleteAllGP(ctx context.Context) int64 {
	rowsAff, err := o.DeleteAll(ctx, boil.GetContextDB())
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o MediaFileSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(mediaFileBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), mediaFilePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"mediaFile\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, mediaFilePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from mediaFile slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for mediaFile")
	}

	if len(mediaFileAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// ReloadG refetches the object from the database using the primary keys.
func (o *MediaFile) ReloadG(ctx context.Context) error {
	if o == nil {
		return errors.New("models: no MediaFile provided for reload")
	}

	return o.Reload(ctx, boil.GetContextDB())
}

// ReloadP refetches the object from the database with an executor. Panics on error.
func (o *MediaFile) ReloadP(ctx context.Context, exec boil.ContextExecutor) {
	if err := o.Reload(ctx, exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadGP refetches the object from the database and panics on error.
func (o *MediaFile) ReloadGP(ctx context.Context) {
	if err := o.Reload(ctx, boil.GetContextDB()); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *MediaFile) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindMediaFile(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *MediaFileSlice) ReloadAllG(ctx context.Context) error {
	if o == nil {
		return errors.New("models: empty MediaFileSlice provided for reload all")
	}

	return o.ReloadAll(ctx, boil.GetContextDB())
}

// ReloadAllP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *MediaFileSlice) ReloadAllP(ctx context.Context, exec boil.ContextExecutor) {
	if err := o.ReloadAll(ctx, exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllGP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *MediaFileSlice) ReloadAllGP(ctx context.Context) {
	if err := o.ReloadAll(ctx, boil.GetContextDB()); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *MediaFileSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := MediaFileSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), mediaFilePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"mediaFile\".* FROM \"mediaFile\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, mediaFilePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in MediaFileSlice")
	}

	*o = slice

	return nil
}

// MediaFileExistsG checks if the MediaFile row exists.
func MediaFileExistsG(ctx context.Context, iD null.Int64) (bool, error) {
	return MediaFileExists(ctx, boil.GetContextDB(), iD)
}

// MediaFileExistsP checks if the MediaFile row exists. Panics on error.
func MediaFileExistsP(ctx context.Context, exec boil.ContextExecutor, iD null.Int64) bool {
	e, err := MediaFileExists(ctx, exec, iD)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// MediaFileExistsGP checks if the MediaFile row exists. Panics on error.
func MediaFileExistsGP(ctx context.Context, iD null.Int64) bool {
	e, err := MediaFileExists(ctx, boil.GetContextDB(), iD)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// MediaFileExists checks if the MediaFile row exists.
func MediaFileExists(ctx context.Context, exec boil.ContextExecutor, iD null.Int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"mediaFile\" where \"id\"=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if mediaFile exists")
	}

	return exists, nil
}

// Exists checks if the MediaFile row exists.
func (o *MediaFile) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return MediaFileExists(ctx, exec, o.ID)
}
