// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testTorrentFiles(t *testing.T) {
	t.Parallel()

	query := TorrentFiles()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testTorrentFilesDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TorrentFile{}
	if err = randomize.Struct(seed, o, torrentFileDBTypes, true, torrentFileColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TorrentFile struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := TorrentFiles().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testTorrentFilesQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TorrentFile{}
	if err = randomize.Struct(seed, o, torrentFileDBTypes, true, torrentFileColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TorrentFile struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := TorrentFiles().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := TorrentFiles().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testTorrentFilesSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TorrentFile{}
	if err = randomize.Struct(seed, o, torrentFileDBTypes, true, torrentFileColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TorrentFile struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := TorrentFileSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := TorrentFiles().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testTorrentFilesExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TorrentFile{}
	if err = randomize.Struct(seed, o, torrentFileDBTypes, true, torrentFileColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TorrentFile struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := TorrentFileExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if TorrentFile exists: %s", err)
	}
	if !e {
		t.Errorf("Expected TorrentFileExists to return true, but got false.")
	}
}

func testTorrentFilesFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TorrentFile{}
	if err = randomize.Struct(seed, o, torrentFileDBTypes, true, torrentFileColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TorrentFile struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	torrentFileFound, err := FindTorrentFile(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if torrentFileFound == nil {
		t.Error("want a record, got nil")
	}
}

func testTorrentFilesBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TorrentFile{}
	if err = randomize.Struct(seed, o, torrentFileDBTypes, true, torrentFileColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TorrentFile struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = TorrentFiles().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testTorrentFilesOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TorrentFile{}
	if err = randomize.Struct(seed, o, torrentFileDBTypes, true, torrentFileColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TorrentFile struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := TorrentFiles().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testTorrentFilesAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	torrentFileOne := &TorrentFile{}
	torrentFileTwo := &TorrentFile{}
	if err = randomize.Struct(seed, torrentFileOne, torrentFileDBTypes, false, torrentFileColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TorrentFile struct: %s", err)
	}
	if err = randomize.Struct(seed, torrentFileTwo, torrentFileDBTypes, false, torrentFileColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TorrentFile struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = torrentFileOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = torrentFileTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := TorrentFiles().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testTorrentFilesCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	torrentFileOne := &TorrentFile{}
	torrentFileTwo := &TorrentFile{}
	if err = randomize.Struct(seed, torrentFileOne, torrentFileDBTypes, false, torrentFileColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TorrentFile struct: %s", err)
	}
	if err = randomize.Struct(seed, torrentFileTwo, torrentFileDBTypes, false, torrentFileColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TorrentFile struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = torrentFileOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = torrentFileTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := TorrentFiles().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func torrentFileBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *TorrentFile) error {
	*o = TorrentFile{}
	return nil
}

func torrentFileAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *TorrentFile) error {
	*o = TorrentFile{}
	return nil
}

func torrentFileAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *TorrentFile) error {
	*o = TorrentFile{}
	return nil
}

func torrentFileBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *TorrentFile) error {
	*o = TorrentFile{}
	return nil
}

func torrentFileAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *TorrentFile) error {
	*o = TorrentFile{}
	return nil
}

func torrentFileBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *TorrentFile) error {
	*o = TorrentFile{}
	return nil
}

func torrentFileAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *TorrentFile) error {
	*o = TorrentFile{}
	return nil
}

func torrentFileBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *TorrentFile) error {
	*o = TorrentFile{}
	return nil
}

func torrentFileAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *TorrentFile) error {
	*o = TorrentFile{}
	return nil
}

func testTorrentFilesHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &TorrentFile{}
	o := &TorrentFile{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, torrentFileDBTypes, false); err != nil {
		t.Errorf("Unable to randomize TorrentFile object: %s", err)
	}

	AddTorrentFileHook(boil.BeforeInsertHook, torrentFileBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	torrentFileBeforeInsertHooks = []TorrentFileHook{}

	AddTorrentFileHook(boil.AfterInsertHook, torrentFileAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	torrentFileAfterInsertHooks = []TorrentFileHook{}

	AddTorrentFileHook(boil.AfterSelectHook, torrentFileAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	torrentFileAfterSelectHooks = []TorrentFileHook{}

	AddTorrentFileHook(boil.BeforeUpdateHook, torrentFileBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	torrentFileBeforeUpdateHooks = []TorrentFileHook{}

	AddTorrentFileHook(boil.AfterUpdateHook, torrentFileAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	torrentFileAfterUpdateHooks = []TorrentFileHook{}

	AddTorrentFileHook(boil.BeforeDeleteHook, torrentFileBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	torrentFileBeforeDeleteHooks = []TorrentFileHook{}

	AddTorrentFileHook(boil.AfterDeleteHook, torrentFileAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	torrentFileAfterDeleteHooks = []TorrentFileHook{}

	AddTorrentFileHook(boil.BeforeUpsertHook, torrentFileBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	torrentFileBeforeUpsertHooks = []TorrentFileHook{}

	AddTorrentFileHook(boil.AfterUpsertHook, torrentFileAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	torrentFileAfterUpsertHooks = []TorrentFileHook{}
}

func testTorrentFilesInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TorrentFile{}
	if err = randomize.Struct(seed, o, torrentFileDBTypes, true, torrentFileColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TorrentFile struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := TorrentFiles().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testTorrentFilesInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TorrentFile{}
	if err = randomize.Struct(seed, o, torrentFileDBTypes, true); err != nil {
		t.Errorf("Unable to randomize TorrentFile struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(torrentFileColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := TorrentFiles().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testTorrentFileToOneEpisodeUsingEpisodeIdEpisode(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local TorrentFile
	var foreign Episode

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, torrentFileDBTypes, true, torrentFileColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TorrentFile struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, episodeDBTypes, true, episodeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Episode struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&local.EpisodeId, foreign.ID)
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.EpisodeIdEpisode().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if !queries.Equal(check.ID, foreign.ID) {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	ranAfterSelectHook := false
	AddEpisodeHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *Episode) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := TorrentFileSlice{&local}
	if err = local.L.LoadEpisodeIdEpisode(ctx, tx, false, (*[]*TorrentFile)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.EpisodeIdEpisode == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.EpisodeIdEpisode = nil
	if err = local.L.LoadEpisodeIdEpisode(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.EpisodeIdEpisode == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testTorrentFileToOneMetaDatumUsingMetaDataIdMetaDatum(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local TorrentFile
	var foreign MetaDatum

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, torrentFileDBTypes, true, torrentFileColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TorrentFile struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, metaDatumDBTypes, true, metaDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MetaDatum struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&local.MetaDataId, foreign.ID)
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.MetaDataIdMetaDatum().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if !queries.Equal(check.ID, foreign.ID) {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	ranAfterSelectHook := false
	AddMetaDatumHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *MetaDatum) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := TorrentFileSlice{&local}
	if err = local.L.LoadMetaDataIdMetaDatum(ctx, tx, false, (*[]*TorrentFile)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.MetaDataIdMetaDatum == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.MetaDataIdMetaDatum = nil
	if err = local.L.LoadMetaDataIdMetaDatum(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.MetaDataIdMetaDatum == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testTorrentFileToOneSetOpEpisodeUsingEpisodeIdEpisode(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a TorrentFile
	var b, c Episode

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, torrentFileDBTypes, false, strmangle.SetComplement(torrentFilePrimaryKeyColumns, torrentFileColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, episodeDBTypes, false, strmangle.SetComplement(episodePrimaryKeyColumns, episodeColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, episodeDBTypes, false, strmangle.SetComplement(episodePrimaryKeyColumns, episodeColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Episode{&b, &c} {
		err = a.SetEpisodeIdEpisode(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.EpisodeIdEpisode != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.EpisodeIdTorrentFiles[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if !queries.Equal(a.EpisodeId, x.ID) {
			t.Error("foreign key was wrong value", a.EpisodeId)
		}

		zero := reflect.Zero(reflect.TypeOf(a.EpisodeId))
		reflect.Indirect(reflect.ValueOf(&a.EpisodeId)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if !queries.Equal(a.EpisodeId, x.ID) {
			t.Error("foreign key was wrong value", a.EpisodeId, x.ID)
		}
	}
}

func testTorrentFileToOneRemoveOpEpisodeUsingEpisodeIdEpisode(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a TorrentFile
	var b Episode

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, torrentFileDBTypes, false, strmangle.SetComplement(torrentFilePrimaryKeyColumns, torrentFileColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, episodeDBTypes, false, strmangle.SetComplement(episodePrimaryKeyColumns, episodeColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = a.SetEpisodeIdEpisode(ctx, tx, true, &b); err != nil {
		t.Fatal(err)
	}

	if err = a.RemoveEpisodeIdEpisode(ctx, tx, &b); err != nil {
		t.Error("failed to remove relationship")
	}

	count, err := a.EpisodeIdEpisode().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 0 {
		t.Error("want no relationships remaining")
	}

	if a.R.EpisodeIdEpisode != nil {
		t.Error("R struct entry should be nil")
	}

	if !queries.IsValuerNil(a.EpisodeId) {
		t.Error("foreign key value should be nil")
	}

	if len(b.R.EpisodeIdTorrentFiles) != 0 {
		t.Error("failed to remove a from b's relationships")
	}
}

func testTorrentFileToOneSetOpMetaDatumUsingMetaDataIdMetaDatum(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a TorrentFile
	var b, c MetaDatum

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, torrentFileDBTypes, false, strmangle.SetComplement(torrentFilePrimaryKeyColumns, torrentFileColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, metaDatumDBTypes, false, strmangle.SetComplement(metaDatumPrimaryKeyColumns, metaDatumColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, metaDatumDBTypes, false, strmangle.SetComplement(metaDatumPrimaryKeyColumns, metaDatumColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*MetaDatum{&b, &c} {
		err = a.SetMetaDataIdMetaDatum(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.MetaDataIdMetaDatum != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.MetaDataIdTorrentFiles[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if !queries.Equal(a.MetaDataId, x.ID) {
			t.Error("foreign key was wrong value", a.MetaDataId)
		}

		zero := reflect.Zero(reflect.TypeOf(a.MetaDataId))
		reflect.Indirect(reflect.ValueOf(&a.MetaDataId)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if !queries.Equal(a.MetaDataId, x.ID) {
			t.Error("foreign key was wrong value", a.MetaDataId, x.ID)
		}
	}
}

func testTorrentFileToOneRemoveOpMetaDatumUsingMetaDataIdMetaDatum(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a TorrentFile
	var b MetaDatum

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, torrentFileDBTypes, false, strmangle.SetComplement(torrentFilePrimaryKeyColumns, torrentFileColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, metaDatumDBTypes, false, strmangle.SetComplement(metaDatumPrimaryKeyColumns, metaDatumColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = a.SetMetaDataIdMetaDatum(ctx, tx, true, &b); err != nil {
		t.Fatal(err)
	}

	if err = a.RemoveMetaDataIdMetaDatum(ctx, tx, &b); err != nil {
		t.Error("failed to remove relationship")
	}

	count, err := a.MetaDataIdMetaDatum().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 0 {
		t.Error("want no relationships remaining")
	}

	if a.R.MetaDataIdMetaDatum != nil {
		t.Error("R struct entry should be nil")
	}

	if !queries.IsValuerNil(a.MetaDataId) {
		t.Error("foreign key value should be nil")
	}

	if len(b.R.MetaDataIdTorrentFiles) != 0 {
		t.Error("failed to remove a from b's relationships")
	}
}

func testTorrentFilesReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TorrentFile{}
	if err = randomize.Struct(seed, o, torrentFileDBTypes, true, torrentFileColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TorrentFile struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testTorrentFilesReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TorrentFile{}
	if err = randomize.Struct(seed, o, torrentFileDBTypes, true, torrentFileColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TorrentFile struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := TorrentFileSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testTorrentFilesSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TorrentFile{}
	if err = randomize.Struct(seed, o, torrentFileDBTypes, true, torrentFileColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TorrentFile struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := TorrentFiles().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	torrentFileDBTypes = map[string]string{`ID`: `INTEGER`, `Raw`: `TEXT`, `Title`: `TEXT`, `Magnet`: `TEXT`, `Size`: `INTEGER`, `Status`: `VARCHAR(10)`, `ScanError`: `TEXT`, `MetaDataId`: `INTEGER`, `EpisodeId`: `INTEGER`, `Year`: `INTEGER`, `Resolution`: `VARCHAR(40)`, `Quality`: `VARCHAR(40)`, `Codec`: `VARCHAR(40)`, `Audio`: `VARCHAR(40)`, `Group`: `VARCHAR(40)`, `Region`: `VARCHAR(40)`, `Language`: `VARCHAR(40)`, `Extended`: `BOOLEAN`, `Hardcoded`: `BOOLEAN`, `Proper`: `BOOLEAN`, `Repack`: `BOOLEAN`, `WideScreen`: `BOOLEAN`, `UploadedAt`: `DATETIME`}
	_                  = bytes.MinRead
)

func testTorrentFilesUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(torrentFilePrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(torrentFileAllColumns) == len(torrentFilePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &TorrentFile{}
	if err = randomize.Struct(seed, o, torrentFileDBTypes, true, torrentFileColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TorrentFile struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := TorrentFiles().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, torrentFileDBTypes, true, torrentFilePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize TorrentFile struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testTorrentFilesSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(torrentFileAllColumns) == len(torrentFilePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &TorrentFile{}
	if err = randomize.Struct(seed, o, torrentFileDBTypes, true, torrentFileColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TorrentFile struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := TorrentFiles().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, torrentFileDBTypes, true, torrentFilePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize TorrentFile struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(torrentFileAllColumns, torrentFilePrimaryKeyColumns) {
		fields = torrentFileAllColumns
	} else {
		fields = strmangle.SetComplement(
			torrentFileAllColumns,
			torrentFilePrimaryKeyColumns,
		)
		fields = strmangle.SetComplement(fields, torrentFileGeneratedColumns)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := TorrentFileSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testTorrentFilesUpsert(t *testing.T) {
	t.Parallel()
	if len(torrentFileAllColumns) == len(torrentFilePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := TorrentFile{}
	if err = randomize.Struct(seed, &o, torrentFileDBTypes, true); err != nil {
		t.Errorf("Unable to randomize TorrentFile struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert TorrentFile: %s", err)
	}

	count, err := TorrentFiles().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, torrentFileDBTypes, false, torrentFilePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize TorrentFile struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert TorrentFile: %s", err)
	}

	count, err = TorrentFiles().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
