// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// TorrentFile is an object representing the database table.
type TorrentFile struct {
	ID         null.Int64  `boil:"id" json:"id,omitempty" toml:"id" yaml:"id,omitempty"`
	Raw        null.String `boil:"raw" json:"raw,omitempty" toml:"raw" yaml:"raw,omitempty"`
	Title      null.String `boil:"title" json:"title,omitempty" toml:"title" yaml:"title,omitempty"`
	Magnet     null.String `boil:"magnet" json:"magnet,omitempty" toml:"magnet" yaml:"magnet,omitempty"`
	Size       null.Int64  `boil:"size" json:"size,omitempty" toml:"size" yaml:"size,omitempty"`
	Status     null.String `boil:"status" json:"status,omitempty" toml:"status" yaml:"status,omitempty"`
	ScanError  null.String `boil:"scanError" json:"scanError,omitempty" toml:"scanError" yaml:"scanError,omitempty"`
	MetaDataId null.Int64  `boil:"metaDataId" json:"metaDataId,omitempty" toml:"metaDataId" yaml:"metaDataId,omitempty"`
	EpisodeId  null.Int64  `boil:"episodeId" json:"episodeId,omitempty" toml:"episodeId" yaml:"episodeId,omitempty"`
	Year       null.Int64  `boil:"year" json:"year,omitempty" toml:"year" yaml:"year,omitempty"`
	Resolution null.String `boil:"resolution" json:"resolution,omitempty" toml:"resolution" yaml:"resolution,omitempty"`
	Quality    null.String `boil:"quality" json:"quality,omitempty" toml:"quality" yaml:"quality,omitempty"`
	Codec      null.String `boil:"codec" json:"codec,omitempty" toml:"codec" yaml:"codec,omitempty"`
	Audio      null.String `boil:"audio" json:"audio,omitempty" toml:"audio" yaml:"audio,omitempty"`
	Group      null.String `boil:"group" json:"group,omitempty" toml:"group" yaml:"group,omitempty"`
	Region     null.String `boil:"region" json:"region,omitempty" toml:"region" yaml:"region,omitempty"`
	Language   null.String `boil:"language" json:"language,omitempty" toml:"language" yaml:"language,omitempty"`
	Extended   null.Bool   `boil:"extended" json:"extended,omitempty" toml:"extended" yaml:"extended,omitempty"`
	Hardcoded  null.Bool   `boil:"hardcoded" json:"hardcoded,omitempty" toml:"hardcoded" yaml:"hardcoded,omitempty"`
	Proper     null.Bool   `boil:"proper" json:"proper,omitempty" toml:"proper" yaml:"proper,omitempty"`
	Repack     null.Bool   `boil:"repack" json:"repack,omitempty" toml:"repack" yaml:"repack,omitempty"`
	WideScreen null.Bool   `boil:"wideScreen" json:"wideScreen,omitempty" toml:"wideScreen" yaml:"wideScreen,omitempty"`
	UploadedAt null.Int64  `boil:"uploadedAt" json:"uploadedAt,omitempty" toml:"uploadedAt" yaml:"uploadedAt,omitempty"`

	R *torrentFileR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L torrentFileL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var TorrentFileColumns = struct {
	ID         string
	Raw        string
	Title      string
	Magnet     string
	Size       string
	Status     string
	ScanError  string
	MetaDataId string
	EpisodeId  string
	Year       string
	Resolution string
	Quality    string
	Codec      string
	Audio      string
	Group      string
	Region     string
	Language   string
	Extended   string
	Hardcoded  string
	Proper     string
	Repack     string
	WideScreen string
	UploadedAt string
}{
	ID:         "id",
	Raw:        "raw",
	Title:      "title",
	Magnet:     "magnet",
	Size:       "size",
	Status:     "status",
	ScanError:  "scanError",
	MetaDataId: "metaDataId",
	EpisodeId:  "episodeId",
	Year:       "year",
	Resolution: "resolution",
	Quality:    "quality",
	Codec:      "codec",
	Audio:      "audio",
	Group:      "group",
	Region:     "region",
	Language:   "language",
	Extended:   "extended",
	Hardcoded:  "hardcoded",
	Proper:     "proper",
	Repack:     "repack",
	WideScreen: "wideScreen",
	UploadedAt: "uploadedAt",
}

var TorrentFileTableColumns = struct {
	ID         string
	Raw        string
	Title      string
	Magnet     string
	Size       string
	Status     string
	ScanError  string
	MetaDataId string
	EpisodeId  string
	Year       string
	Resolution string
	Quality    string
	Codec      string
	Audio      string
	Group      string
	Region     string
	Language   string
	Extended   string
	Hardcoded  string
	Proper     string
	Repack     string
	WideScreen string
	UploadedAt string
}{
	ID:         "torrentFile.id",
	Raw:        "torrentFile.raw",
	Title:      "torrentFile.title",
	Magnet:     "torrentFile.magnet",
	Size:       "torrentFile.size",
	Status:     "torrentFile.status",
	ScanError:  "torrentFile.scanError",
	MetaDataId: "torrentFile.metaDataId",
	EpisodeId:  "torrentFile.episodeId",
	Year:       "torrentFile.year",
	Resolution: "torrentFile.resolution",
	Quality:    "torrentFile.quality",
	Codec:      "torrentFile.codec",
	Audio:      "torrentFile.audio",
	Group:      "torrentFile.group",
	Region:     "torrentFile.region",
	Language:   "torrentFile.language",
	Extended:   "torrentFile.extended",
	Hardcoded:  "torrentFile.hardcoded",
	Proper:     "torrentFile.proper",
	Repack:     "torrentFile.repack",
	WideScreen: "torrentFile.wideScreen",
	UploadedAt: "torrentFile.uploadedAt",
}

// Generated where

var TorrentFileWhere = struct {
	ID         whereHelpernull_Int64
	Raw        whereHelpernull_String
	Title      whereHelpernull_String
	Magnet     whereHelpernull_String
	Size       whereHelpernull_Int64
	Status     whereHelpernull_String
	ScanError  whereHelpernull_String
	MetaDataId whereHelpernull_Int64
	EpisodeId  whereHelpernull_Int64
	Year       whereHelpernull_Int64
	Resolution whereHelpernull_String
	Quality    whereHelpernull_String
	Codec      whereHelpernull_String
	Audio      whereHelpernull_String
	Group      whereHelpernull_String
	Region     whereHelpernull_String
	Language   whereHelpernull_String
	Extended   whereHelpernull_Bool
	Hardcoded  whereHelpernull_Bool
	Proper     whereHelpernull_Bool
	Repack     whereHelpernull_Bool
	WideScreen whereHelpernull_Bool
	UploadedAt whereHelpernull_Int64
}{
	ID:         whereHelpernull_Int64{field: "\"torrentFile\".\"id\""},
	Raw:        whereHelpernull_String{field: "\"torrentFile\".\"raw\""},
	Title:      whereHelpernull_String{field: "\"torrentFile\".\"title\""},
	Magnet:     whereHelpernull_String{field: "\"torrentFile\".\"magnet\""},
	Size:       whereHelpernull_Int64{field: "\"torrentFile\".\"size\""},
	Status:     whereHelpernull_String{field: "\"torrentFile\".\"status\""},
	ScanError:  whereHelpernull_String{field: "\"torrentFile\".\"scanError\""},
	MetaDataId: whereHelpernull_Int64{field: "\"torrentFile\".\"metaDataId\""},
	EpisodeId:  whereHelpernull_Int64{field: "\"torrentFile\".\"episodeId\""},
	Year:       whereHelpernull_Int64{field: "\"torrentFile\".\"year\""},
	Resolution: whereHelpernull_String{field: "\"torrentFile\".\"resolution\""},
	Quality:    whereHelpernull_String{field: "\"torrentFile\".\"quality\""},
	Codec:      whereHelpernull_String{field: "\"torrentFile\".\"codec\""},
	Audio:      whereHelpernull_String{field: "\"torrentFile\".\"audio\""},
	Group:      whereHelpernull_String{field: "\"torrentFile\".\"group\""},
	Region:     whereHelpernull_String{field: "\"torrentFile\".\"region\""},
	Language:   whereHelpernull_String{field: "\"torrentFile\".\"language\""},
	Extended:   whereHelpernull_Bool{field: "\"torrentFile\".\"extended\""},
	Hardcoded:  whereHelpernull_Bool{field: "\"torrentFile\".\"hardcoded\""},
	Proper:     whereHelpernull_Bool{field: "\"torrentFile\".\"proper\""},
	Repack:     whereHelpernull_Bool{field: "\"torrentFile\".\"repack\""},
	WideScreen: whereHelpernull_Bool{field: "\"torrentFile\".\"wideScreen\""},
	UploadedAt: whereHelpernull_Int64{field: "\"torrentFile\".\"uploadedAt\""},
}

// TorrentFileRels is where relationship names are stored.
var TorrentFileRels = struct {
	EpisodeIdEpisode    string
	MetaDataIdMetaDatum string
}{
	EpisodeIdEpisode:    "EpisodeIdEpisode",
	MetaDataIdMetaDatum: "MetaDataIdMetaDatum",
}

// torrentFileR is where relationships are stored.
type torrentFileR struct {
	EpisodeIdEpisode    *Episode   `boil:"EpisodeIdEpisode" json:"EpisodeIdEpisode" toml:"EpisodeIdEpisode" yaml:"EpisodeIdEpisode"`
	MetaDataIdMetaDatum *MetaDatum `boil:"MetaDataIdMetaDatum" json:"MetaDataIdMetaDatum" toml:"MetaDataIdMetaDatum" yaml:"MetaDataIdMetaDatum"`
}

// NewStruct creates a new relationship struct
func (*torrentFileR) NewStruct() *torrentFileR {
	return &torrentFileR{}
}

func (r *torrentFileR) GetEpisodeIdEpisode() *Episode {
	if r == nil {
		return nil
	}
	return r.EpisodeIdEpisode
}

func (r *torrentFileR) GetMetaDataIdMetaDatum() *MetaDatum {
	if r == nil {
		return nil
	}
	return r.MetaDataIdMetaDatum
}

// torrentFileL is where Load methods for each relationship are stored.
type torrentFileL struct{}

var (
	torrentFileAllColumns            = []string{"id", "raw", "title", "magnet", "size", "status", "scanError", "metaDataId", "episodeId", "year", "resolution", "quality", "codec", "audio", "group", "region", "language", "extended", "hardcoded", "proper", "repack", "wideScreen", "uploadedAt"}
	torrentFileColumnsWithoutDefault = []string{}
	torrentFileColumnsWithDefault    = []string{"id", "raw", "title", "magnet", "size", "status", "scanError", "metaDataId", "episodeId", "year", "resolution", "quality", "codec", "audio", "group", "region", "language", "extended", "hardcoded", "proper", "repack", "wideScreen", "uploadedAt"}
	torrentFilePrimaryKeyColumns     = []string{"id"}
	torrentFileGeneratedColumns      = []string{"id"}
)

type (
	// TorrentFileSlice is an alias for a slice of pointers to TorrentFile.
	// This should almost always be used instead of []TorrentFile.
	TorrentFileSlice []*TorrentFile
	// TorrentFileHook is the signature for custom TorrentFile hook methods
	TorrentFileHook func(context.Context, boil.ContextExecutor, *TorrentFile) error

	torrentFileQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	torrentFileType                 = reflect.TypeOf(&TorrentFile{})
	torrentFileMapping              = queries.MakeStructMapping(torrentFileType)
	torrentFilePrimaryKeyMapping, _ = queries.BindMapping(torrentFileType, torrentFileMapping, torrentFilePrimaryKeyColumns)
	torrentFileInsertCacheMut       sync.RWMutex
	torrentFileInsertCache          = make(map[string]insertCache)
	torrentFileUpdateCacheMut       sync.RWMutex
	torrentFileUpdateCache          = make(map[string]updateCache)
	torrentFileUpsertCacheMut       sync.RWMutex
	torrentFileUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var torrentFileAfterSelectMu sync.Mutex
var torrentFileAfterSelectHooks []TorrentFileHook

var torrentFileBeforeInsertMu sync.Mutex
var torrentFileBeforeInsertHooks []TorrentFileHook
var torrentFileAfterInsertMu sync.Mutex
var torrentFileAfterInsertHooks []TorrentFileHook

var torrentFileBeforeUpdateMu sync.Mutex
var torrentFileBeforeUpdateHooks []TorrentFileHook
var torrentFileAfterUpdateMu sync.Mutex
var torrentFileAfterUpdateHooks []TorrentFileHook

var torrentFileBeforeDeleteMu sync.Mutex
var torrentFileBeforeDeleteHooks []TorrentFileHook
var torrentFileAfterDeleteMu sync.Mutex
var torrentFileAfterDeleteHooks []TorrentFileHook

var torrentFileBeforeUpsertMu sync.Mutex
var torrentFileBeforeUpsertHooks []TorrentFileHook
var torrentFileAfterUpsertMu sync.Mutex
var torrentFileAfterUpsertHooks []TorrentFileHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *TorrentFile) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range torrentFileAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *TorrentFile) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range torrentFileBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *TorrentFile) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range torrentFileAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *TorrentFile) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range torrentFileBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *TorrentFile) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range torrentFileAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *TorrentFile) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range torrentFileBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *TorrentFile) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range torrentFileAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *TorrentFile) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range torrentFileBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *TorrentFile) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range torrentFileAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddTorrentFileHook registers your hook function for all future operations.
func AddTorrentFileHook(hookPoint boil.HookPoint, torrentFileHook TorrentFileHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		torrentFileAfterSelectMu.Lock()
		torrentFileAfterSelectHooks = append(torrentFileAfterSelectHooks, torrentFileHook)
		torrentFileAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		torrentFileBeforeInsertMu.Lock()
		torrentFileBeforeInsertHooks = append(torrentFileBeforeInsertHooks, torrentFileHook)
		torrentFileBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		torrentFileAfterInsertMu.Lock()
		torrentFileAfterInsertHooks = append(torrentFileAfterInsertHooks, torrentFileHook)
		torrentFileAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		torrentFileBeforeUpdateMu.Lock()
		torrentFileBeforeUpdateHooks = append(torrentFileBeforeUpdateHooks, torrentFileHook)
		torrentFileBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		torrentFileAfterUpdateMu.Lock()
		torrentFileAfterUpdateHooks = append(torrentFileAfterUpdateHooks, torrentFileHook)
		torrentFileAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		torrentFileBeforeDeleteMu.Lock()
		torrentFileBeforeDeleteHooks = append(torrentFileBeforeDeleteHooks, torrentFileHook)
		torrentFileBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		torrentFileAfterDeleteMu.Lock()
		torrentFileAfterDeleteHooks = append(torrentFileAfterDeleteHooks, torrentFileHook)
		torrentFileAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		torrentFileBeforeUpsertMu.Lock()
		torrentFileBeforeUpsertHooks = append(torrentFileBeforeUpsertHooks, torrentFileHook)
		torrentFileBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		torrentFileAfterUpsertMu.Lock()
		torrentFileAfterUpsertHooks = append(torrentFileAfterUpsertHooks, torrentFileHook)
		torrentFileAfterUpsertMu.Unlock()
	}
}

// OneG returns a single torrentFile record from the query using the global executor.
func (q torrentFileQuery) OneG(ctx context.Context) (*TorrentFile, error) {
	return q.One(ctx, boil.GetContextDB())
}

// OneGP returns a single torrentFile record from the query using the global executor, and panics on error.
func (q torrentFileQuery) OneGP(ctx context.Context) *TorrentFile {
	o, err := q.One(ctx, boil.GetContextDB())
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// OneP returns a single torrentFile record from the query, and panics on error.
func (q torrentFileQuery) OneP(ctx context.Context, exec boil.ContextExecutor) *TorrentFile {
	o, err := q.One(ctx, exec)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// One returns a single torrentFile record from the query.
func (q torrentFileQuery) One(ctx context.Context, exec boil.ContextExecutor) (*TorrentFile, error) {
	o := &TorrentFile{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for torrentFile")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// AllG returns all TorrentFile records from the query using the global executor.
func (q torrentFileQuery) AllG(ctx context.Context) (TorrentFileSlice, error) {
	return q.All(ctx, boil.GetContextDB())
}

// AllGP returns all TorrentFile records from the query using the global executor, and panics on error.
func (q torrentFileQuery) AllGP(ctx context.Context) TorrentFileSlice {
	o, err := q.All(ctx, boil.GetContextDB())
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// AllP returns all TorrentFile records from the query, and panics on error.
func (q torrentFileQuery) AllP(ctx context.Context, exec boil.ContextExecutor) TorrentFileSlice {
	o, err := q.All(ctx, exec)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// All returns all TorrentFile records from the query.
func (q torrentFileQuery) All(ctx context.Context, exec boil.ContextExecutor) (TorrentFileSlice, error) {
	var o []*TorrentFile

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to TorrentFile slice")
	}

	if len(torrentFileAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountG returns the count of all TorrentFile records in the query using the global executor
func (q torrentFileQuery) CountG(ctx context.Context) (int64, error) {
	return q.Count(ctx, boil.GetContextDB())
}

// CountGP returns the count of all TorrentFile records in the query using the global executor, and panics on error.
func (q torrentFileQuery) CountGP(ctx context.Context) int64 {
	c, err := q.Count(ctx, boil.GetContextDB())
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return c
}

// CountP returns the count of all TorrentFile records in the query, and panics on error.
func (q torrentFileQuery) CountP(ctx context.Context, exec boil.ContextExecutor) int64 {
	c, err := q.Count(ctx, exec)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return c
}

// Count returns the count of all TorrentFile records in the query.
func (q torrentFileQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count torrentFile rows")
	}

	return count, nil
}

// ExistsG checks if the row exists in the table using the global executor.
func (q torrentFileQuery) ExistsG(ctx context.Context) (bool, error) {
	return q.Exists(ctx, boil.GetContextDB())
}

// ExistsGP checks if the row exists in the table using the global executor, and panics on error.
func (q torrentFileQuery) ExistsGP(ctx context.Context) bool {
	e, err := q.Exists(ctx, boil.GetContextDB())
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// ExistsP checks if the row exists in the table, and panics on error.
func (q torrentFileQuery) ExistsP(ctx context.Context, exec boil.ContextExecutor) bool {
	e, err := q.Exists(ctx, exec)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// Exists checks if the row exists in the table.
func (q torrentFileQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if torrentFile exists")
	}

	return count > 0, nil
}

// EpisodeIdEpisode pointed to by the foreign key.
func (o *TorrentFile) EpisodeIdEpisode(mods ...qm.QueryMod) episodeQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.EpisodeId),
	}

	queryMods = append(queryMods, mods...)

	return Episodes(queryMods...)
}

// MetaDataIdMetaDatum pointed to by the foreign key.
func (o *TorrentFile) MetaDataIdMetaDatum(mods ...qm.QueryMod) metaDatumQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.MetaDataId),
	}

	queryMods = append(queryMods, mods...)

	return MetaData(queryMods...)
}

// LoadEpisodeIdEpisode allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (torrentFileL) LoadEpisodeIdEpisode(ctx context.Context, e boil.ContextExecutor, singular bool, maybeTorrentFile interface{}, mods queries.Applicator) error {
	var slice []*TorrentFile
	var object *TorrentFile

	if singular {
		var ok bool
		object, ok = maybeTorrentFile.(*TorrentFile)
		if !ok {
			object = new(TorrentFile)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeTorrentFile)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeTorrentFile))
			}
		}
	} else {
		s, ok := maybeTorrentFile.(*[]*TorrentFile)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeTorrentFile)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeTorrentFile))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &torrentFileR{}
		}
		if !queries.IsNil(object.EpisodeId) {
			args[object.EpisodeId] = struct{}{}
		}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &torrentFileR{}
			}

			if !queries.IsNil(obj.EpisodeId) {
				args[obj.EpisodeId] = struct{}{}
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`episode`),
		qm.WhereIn(`episode.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Episode")
	}

	var resultSlice []*Episode
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Episode")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for episode")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for episode")
	}

	if len(episodeAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.EpisodeIdEpisode = foreign
		if foreign.R == nil {
			foreign.R = &episodeR{}
		}
		foreign.R.EpisodeIdTorrentFiles = append(foreign.R.EpisodeIdTorrentFiles, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.EpisodeId, foreign.ID) {
				local.R.EpisodeIdEpisode = foreign
				if foreign.R == nil {
					foreign.R = &episodeR{}
				}
				foreign.R.EpisodeIdTorrentFiles = append(foreign.R.EpisodeIdTorrentFiles, local)
				break
			}
		}
	}

	return nil
}

// LoadMetaDataIdMetaDatum allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (torrentFileL) LoadMetaDataIdMetaDatum(ctx context.Context, e boil.ContextExecutor, singular bool, maybeTorrentFile interface{}, mods queries.Applicator) error {
	var slice []*TorrentFile
	var object *TorrentFile

	if singular {
		var ok bool
		object, ok = maybeTorrentFile.(*TorrentFile)
		if !ok {
			object = new(TorrentFile)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeTorrentFile)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeTorrentFile))
			}
		}
	} else {
		s, ok := maybeTorrentFile.(*[]*TorrentFile)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeTorrentFile)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeTorrentFile))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &torrentFileR{}
		}
		if !queries.IsNil(object.MetaDataId) {
			args[object.MetaDataId] = struct{}{}
		}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &torrentFileR{}
			}

			if !queries.IsNil(obj.MetaDataId) {
				args[obj.MetaDataId] = struct{}{}
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`metaData`),
		qm.WhereIn(`metaData.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load MetaDatum")
	}

	var resultSlice []*MetaDatum
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice MetaDatum")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for metaData")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for metaData")
	}

	if len(metaDatumAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.MetaDataIdMetaDatum = foreign
		if foreign.R == nil {
			foreign.R = &metaDatumR{}
		}
		foreign.R.MetaDataIdTorrentFiles = append(foreign.R.MetaDataIdTorrentFiles, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.MetaDataId, foreign.ID) {
				local.R.MetaDataIdMetaDatum = foreign
				if foreign.R == nil {
					foreign.R = &metaDatumR{}
				}
				foreign.R.MetaDataIdTorrentFiles = append(foreign.R.MetaDataIdTorrentFiles, local)
				break
			}
		}
	}

	return nil
}

// SetEpisodeIdEpisodeG of the torrentFile to the related item.
// Sets o.R.EpisodeIdEpisode to related.
// Adds o to related.R.EpisodeIdTorrentFiles.
// Uses the global database handle.
func (o *TorrentFile) SetEpisodeIdEpisodeG(ctx context.Context, insert bool, related *Episode) error {
	return o.SetEpisodeIdEpisode(ctx, boil.GetContextDB(), insert, related)
}

// SetEpisodeIdEpisodeP of the torrentFile to the related item.
// Sets o.R.EpisodeIdEpisode to related.
// Adds o to related.R.EpisodeIdTorrentFiles.
// Panics on error.
func (o *TorrentFile) SetEpisodeIdEpisodeP(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Episode) {
	if err := o.SetEpisodeIdEpisode(ctx, exec, insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetEpisodeIdEpisodeGP of the torrentFile to the related item.
// Sets o.R.EpisodeIdEpisode to related.
// Adds o to related.R.EpisodeIdTorrentFiles.
// Uses the global database handle and panics on error.
func (o *TorrentFile) SetEpisodeIdEpisodeGP(ctx context.Context, insert bool, related *Episode) {
	if err := o.SetEpisodeIdEpisode(ctx, boil.GetContextDB(), insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetEpisodeIdEpisode of the torrentFile to the related item.
// Sets o.R.EpisodeIdEpisode to related.
// Adds o to related.R.EpisodeIdTorrentFiles.
func (o *TorrentFile) SetEpisodeIdEpisode(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Episode) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"torrentFile\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 0, []string{"episodeId"}),
		strmangle.WhereClause("\"", "\"", 0, torrentFilePrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.EpisodeId, related.ID)
	if o.R == nil {
		o.R = &torrentFileR{
			EpisodeIdEpisode: related,
		}
	} else {
		o.R.EpisodeIdEpisode = related
	}

	if related.R == nil {
		related.R = &episodeR{
			EpisodeIdTorrentFiles: TorrentFileSlice{o},
		}
	} else {
		related.R.EpisodeIdTorrentFiles = append(related.R.EpisodeIdTorrentFiles, o)
	}

	return nil
}

// RemoveEpisodeIdEpisodeG relationship.
// Sets o.R.EpisodeIdEpisode to nil.
// Removes o from all passed in related items' relationships struct.
// Uses the global database handle.
func (o *TorrentFile) RemoveEpisodeIdEpisodeG(ctx context.Context, related *Episode) error {
	return o.RemoveEpisodeIdEpisode(ctx, boil.GetContextDB(), related)
}

// RemoveEpisodeIdEpisodeP relationship.
// Sets o.R.EpisodeIdEpisode to nil.
// Removes o from all passed in related items' relationships struct.
// Panics on error.
func (o *TorrentFile) RemoveEpisodeIdEpisodeP(ctx context.Context, exec boil.ContextExecutor, related *Episode) {
	if err := o.RemoveEpisodeIdEpisode(ctx, exec, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// RemoveEpisodeIdEpisodeGP relationship.
// Sets o.R.EpisodeIdEpisode to nil.
// Removes o from all passed in related items' relationships struct.
// Uses the global database handle and panics on error.
func (o *TorrentFile) RemoveEpisodeIdEpisodeGP(ctx context.Context, related *Episode) {
	if err := o.RemoveEpisodeIdEpisode(ctx, boil.GetContextDB(), related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// RemoveEpisodeIdEpisode relationship.
// Sets o.R.EpisodeIdEpisode to nil.
// Removes o from all passed in related items' relationships struct.
func (o *TorrentFile) RemoveEpisodeIdEpisode(ctx context.Context, exec boil.ContextExecutor, related *Episode) error {
	var err error

	queries.SetScanner(&o.EpisodeId, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("episodeId")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.EpisodeIdEpisode = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.EpisodeIdTorrentFiles {
		if queries.Equal(o.EpisodeId, ri.EpisodeId) {
			continue
		}

		ln := len(related.R.EpisodeIdTorrentFiles)
		if ln > 1 && i < ln-1 {
			related.R.EpisodeIdTorrentFiles[i] = related.R.EpisodeIdTorrentFiles[ln-1]
		}
		related.R.EpisodeIdTorrentFiles = related.R.EpisodeIdTorrentFiles[:ln-1]
		break
	}
	return nil
}

// SetMetaDataIdMetaDatumG of the torrentFile to the related item.
// Sets o.R.MetaDataIdMetaDatum to related.
// Adds o to related.R.MetaDataIdTorrentFiles.
// Uses the global database handle.
func (o *TorrentFile) SetMetaDataIdMetaDatumG(ctx context.Context, insert bool, related *MetaDatum) error {
	return o.SetMetaDataIdMetaDatum(ctx, boil.GetContextDB(), insert, related)
}

// SetMetaDataIdMetaDatumP of the torrentFile to the related item.
// Sets o.R.MetaDataIdMetaDatum to related.
// Adds o to related.R.MetaDataIdTorrentFiles.
// Panics on error.
func (o *TorrentFile) SetMetaDataIdMetaDatumP(ctx context.Context, exec boil.ContextExecutor, insert bool, related *MetaDatum) {
	if err := o.SetMetaDataIdMetaDatum(ctx, exec, insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetMetaDataIdMetaDatumGP of the torrentFile to the related item.
// Sets o.R.MetaDataIdMetaDatum to related.
// Adds o to related.R.MetaDataIdTorrentFiles.
// Uses the global database handle and panics on error.
func (o *TorrentFile) SetMetaDataIdMetaDatumGP(ctx context.Context, insert bool, related *MetaDatum) {
	if err := o.SetMetaDataIdMetaDatum(ctx, boil.GetContextDB(), insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetMetaDataIdMetaDatum of the torrentFile to the related item.
// Sets o.R.MetaDataIdMetaDatum to related.
// Adds o to related.R.MetaDataIdTorrentFiles.
func (o *TorrentFile) SetMetaDataIdMetaDatum(ctx context.Context, exec boil.ContextExecutor, insert bool, related *MetaDatum) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"torrentFile\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 0, []string{"metaDataId"}),
		strmangle.WhereClause("\"", "\"", 0, torrentFilePrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.MetaDataId, related.ID)
	if o.R == nil {
		o.R = &torrentFileR{
			MetaDataIdMetaDatum: related,
		}
	} else {
		o.R.MetaDataIdMetaDatum = related
	}

	if related.R == nil {
		related.R = &metaDatumR{
			MetaDataIdTorrentFiles: TorrentFileSlice{o},
		}
	} else {
		related.R.MetaDataIdTorrentFiles = append(related.R.MetaDataIdTorrentFiles, o)
	}

	return nil
}

// RemoveMetaDataIdMetaDatumG relationship.
// Sets o.R.MetaDataIdMetaDatum to nil.
// Removes o from all passed in related items' relationships struct.
// Uses the global database handle.
func (o *TorrentFile) RemoveMetaDataIdMetaDatumG(ctx context.Context, related *MetaDatum) error {
	return o.RemoveMetaDataIdMetaDatum(ctx, boil.GetContextDB(), related)
}

// RemoveMetaDataIdMetaDatumP relationship.
// Sets o.R.MetaDataIdMetaDatum to nil.
// Removes o from all passed in related items' relationships struct.
// Panics on error.
func (o *TorrentFile) RemoveMetaDataIdMetaDatumP(ctx context.Context, exec boil.ContextExecutor, related *MetaDatum) {
	if err := o.RemoveMetaDataIdMetaDatum(ctx, exec, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// RemoveMetaDataIdMetaDatumGP relationship.
// Sets o.R.MetaDataIdMetaDatum to nil.
// Removes o from all passed in related items' relationships struct.
// Uses the global database handle and panics on error.
func (o *TorrentFile) RemoveMetaDataIdMetaDatumGP(ctx context.Context, related *MetaDatum) {
	if err := o.RemoveMetaDataIdMetaDatum(ctx, boil.GetContextDB(), related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// RemoveMetaDataIdMetaDatum relationship.
// Sets o.R.MetaDataIdMetaDatum to nil.
// Removes o from all passed in related items' relationships struct.
func (o *TorrentFile) RemoveMetaDataIdMetaDatum(ctx context.Context, exec boil.ContextExecutor, related *MetaDatum) error {
	var err error

	queries.SetScanner(&o.MetaDataId, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("metaDataId")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.MetaDataIdMetaDatum = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.MetaDataIdTorrentFiles {
		if queries.Equal(o.MetaDataId, ri.MetaDataId) {
			continue
		}

		ln := len(related.R.MetaDataIdTorrentFiles)
		if ln > 1 && i < ln-1 {
			related.R.MetaDataIdTorrentFiles[i] = related.R.MetaDataIdTorrentFiles[ln-1]
		}
		related.R.MetaDataIdTorrentFiles = related.R.MetaDataIdTorrentFiles[:ln-1]
		break
	}
	return nil
}

// TorrentFiles retrieves all the records using an executor.
func TorrentFiles(mods ...qm.QueryMod) torrentFileQuery {
	mods = append(mods, qm.From("\"torrentFile\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"torrentFile\".*"})
	}

	return torrentFileQuery{q}
}

// FindTorrentFileG retrieves a single record by ID.
func FindTorrentFileG(ctx context.Context, iD null.Int64, selectCols ...string) (*TorrentFile, error) {
	return FindTorrentFile(ctx, boil.GetContextDB(), iD, selectCols...)
}

// FindTorrentFileP retrieves a single record by ID with an executor, and panics on error.
func FindTorrentFileP(ctx context.Context, exec boil.ContextExecutor, iD null.Int64, selectCols ...string) *TorrentFile {
	retobj, err := FindTorrentFile(ctx, exec, iD, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// FindTorrentFileGP retrieves a single record by ID, and panics on error.
func FindTorrentFileGP(ctx context.Context, iD null.Int64, selectCols ...string) *TorrentFile {
	retobj, err := FindTorrentFile(ctx, boil.GetContextDB(), iD, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// FindTorrentFile retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindTorrentFile(ctx context.Context, exec boil.ContextExecutor, iD null.Int64, selectCols ...string) (*TorrentFile, error) {
	torrentFileObj := &TorrentFile{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"torrentFile\" where \"id\"=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, torrentFileObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from torrentFile")
	}

	if err = torrentFileObj.doAfterSelectHooks(ctx, exec); err != nil {
		return torrentFileObj, err
	}

	return torrentFileObj, nil
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *TorrentFile) InsertG(ctx context.Context, columns boil.Columns) error {
	return o.Insert(ctx, boil.GetContextDB(), columns)
}

// InsertP a single record using an executor, and panics on error. See Insert
// for whitelist behavior description.
func (o *TorrentFile) InsertP(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) {
	if err := o.Insert(ctx, exec, columns); err != nil {
		panic(boil.WrapErr(err))
	}
}

// InsertGP a single record, and panics on error. See Insert for whitelist
// behavior description.
func (o *TorrentFile) InsertGP(ctx context.Context, columns boil.Columns) {
	if err := o.Insert(ctx, boil.GetContextDB(), columns); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *TorrentFile) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no torrentFile provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(torrentFileColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	torrentFileInsertCacheMut.RLock()
	cache, cached := torrentFileInsertCache[key]
	torrentFileInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			torrentFileAllColumns,
			torrentFileColumnsWithDefault,
			torrentFileColumnsWithoutDefault,
			nzDefaults,
		)
		wl = strmangle.SetComplement(wl, torrentFileGeneratedColumns)

		cache.valueMapping, err = queries.BindMapping(torrentFileType, torrentFileMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(torrentFileType, torrentFileMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"torrentFile\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"torrentFile\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into torrentFile")
	}

	if !cached {
		torrentFileInsertCacheMut.Lock()
		torrentFileInsertCache[key] = cache
		torrentFileInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// UpdateG a single TorrentFile record using the global executor.
// See Update for more documentation.
func (o *TorrentFile) UpdateG(ctx context.Context, columns boil.Columns) (int64, error) {
	return o.Update(ctx, boil.GetContextDB(), columns)
}

// UpdateP uses an executor to update the TorrentFile, and panics on error.
// See Update for more documentation.
func (o *TorrentFile) UpdateP(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) int64 {
	rowsAff, err := o.Update(ctx, exec, columns)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// UpdateGP a single TorrentFile record using the global executor. Panics on error.
// See Update for more documentation.
func (o *TorrentFile) UpdateGP(ctx context.Context, columns boil.Columns) int64 {
	rowsAff, err := o.Update(ctx, boil.GetContextDB(), columns)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// Update uses an executor to update the TorrentFile.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *TorrentFile) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	torrentFileUpdateCacheMut.RLock()
	cache, cached := torrentFileUpdateCache[key]
	torrentFileUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			torrentFileAllColumns,
			torrentFilePrimaryKeyColumns,
		)
		wl = strmangle.SetComplement(wl, torrentFileGeneratedColumns)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update torrentFile, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"torrentFile\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 0, wl),
			strmangle.WhereClause("\"", "\"", 0, torrentFilePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(torrentFileType, torrentFileMapping, append(wl, torrentFilePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update torrentFile row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for torrentFile")
	}

	if !cached {
		torrentFileUpdateCacheMut.Lock()
		torrentFileUpdateCache[key] = cache
		torrentFileUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAllP updates all rows with matching column names, and panics on error.
func (q torrentFileQuery) UpdateAllP(ctx context.Context, exec boil.ContextExecutor, cols M) int64 {
	rowsAff, err := q.UpdateAll(ctx, exec, cols)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// UpdateAllG updates all rows with the specified column values.
func (q torrentFileQuery) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return q.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAllGP updates all rows with the specified column values, and panics on error.
func (q torrentFileQuery) UpdateAllGP(ctx context.Context, cols M) int64 {
	rowsAff, err := q.UpdateAll(ctx, boil.GetContextDB(), cols)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// UpdateAll updates all rows with the specified column values.
func (q torrentFileQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for torrentFile")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for torrentFile")
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (o TorrentFileSlice) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return o.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAllGP updates all rows with the specified column values, and panics on error.
func (o TorrentFileSlice) UpdateAllGP(ctx context.Context, cols M) int64 {
	rowsAff, err := o.UpdateAll(ctx, boil.GetContextDB(), cols)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// UpdateAllP updates all rows with the specified column values, and panics on error.
func (o TorrentFileSlice) UpdateAllP(ctx context.Context, exec boil.ContextExecutor, cols M) int64 {
	rowsAff, err := o.UpdateAll(ctx, exec, cols)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o TorrentFileSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), torrentFilePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"torrentFile\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, torrentFilePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in torrentFile slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all torrentFile")
	}
	return rowsAff, nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *TorrentFile) UpsertG(ctx context.Context, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	return o.Upsert(ctx, boil.GetContextDB(), updateOnConflict, conflictColumns, updateColumns, insertColumns)
}

// UpsertGP attempts an insert, and does an update or ignore on conflict. Panics on error.
func (o *TorrentFile) UpsertGP(ctx context.Context, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) {
	if err := o.Upsert(ctx, boil.GetContextDB(), updateOnConflict, conflictColumns, updateColumns, insertColumns); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpsertP attempts an insert using an executor, and does an update or ignore on conflict.
// UpsertP panics on error.
func (o *TorrentFile) UpsertP(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) {
	if err := o.Upsert(ctx, exec, updateOnConflict, conflictColumns, updateColumns, insertColumns); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *TorrentFile) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no torrentFile provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(torrentFileColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	torrentFileUpsertCacheMut.RLock()
	cache, cached := torrentFileUpsertCache[key]
	torrentFileUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			torrentFileAllColumns,
			torrentFileColumnsWithDefault,
			torrentFileColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			torrentFileAllColumns,
			torrentFilePrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert torrentFile, could not build update column list")
		}

		ret := strmangle.SetComplement(torrentFileAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(torrentFilePrimaryKeyColumns))
			copy(conflict, torrentFilePrimaryKeyColumns)
		}
		cache.query = buildUpsertQuerySQLite(dialect, "\"torrentFile\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(torrentFileType, torrentFileMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(torrentFileType, torrentFileMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert torrentFile")
	}

	if !cached {
		torrentFileUpsertCacheMut.Lock()
		torrentFileUpsertCache[key] = cache
		torrentFileUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// DeleteG deletes a single TorrentFile record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *TorrentFile) DeleteG(ctx context.Context) (int64, error) {
	return o.Delete(ctx, boil.GetContextDB())
}

// DeleteP deletes a single TorrentFile record with an executor.
// DeleteP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *TorrentFile) DeleteP(ctx context.Context, exec boil.ContextExecutor) int64 {
	rowsAff, err := o.Delete(ctx, exec)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// DeleteGP deletes a single TorrentFile record.
// DeleteGP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *TorrentFile) DeleteGP(ctx context.Context) int64 {
	rowsAff, err := o.Delete(ctx, boil.GetContextDB())
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// Delete deletes a single TorrentFile record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *TorrentFile) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no TorrentFile provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), torrentFilePrimaryKeyMapping)
	sql := "DELETE FROM \"torrentFile\" WHERE \"id\"=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from torrentFile")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for torrentFile")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

func (q torrentFileQuery) DeleteAllG(ctx context.Context) (int64, error) {
	return q.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAllP deletes all rows, and panics on error.
func (q torrentFileQuery) DeleteAllP(ctx context.Context, exec boil.ContextExecutor) int64 {
	rowsAff, err := q.DeleteAll(ctx, exec)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// DeleteAllGP deletes all rows, and panics on error.
func (q torrentFileQuery) DeleteAllGP(ctx context.Context) int64 {
	rowsAff, err := q.DeleteAll(ctx, boil.GetContextDB())
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// DeleteAll deletes all matching rows.
func (q torrentFileQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no torrentFileQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from torrentFile")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for torrentFile")
	}

	return rowsAff, nil
}

// DeleteAllG deletes all rows in the slice.
func (o TorrentFileSlice) DeleteAllG(ctx context.Context) (int64, error) {
	return o.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAllP deletes all rows in the slice, using an executor, and panics on error.
func (o TorrentFileSlice) DeleteAllP(ctx context.Context, exec boil.ContextExecutor) int64 {
	rowsAff, err := o.DeleteAll(ctx, exec)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// DeleteAllGP deletes all rows in the slice, and panics on error.
func (o TorrentFileSlice) DeleteAllGP(ctx context.Context) int64 {
	rowsAff, err := o.DeleteAll(ctx, boil.GetContextDB())
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o TorrentFileSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(torrentFileBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), torrentFilePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"torrentFile\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, torrentFilePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from torrentFile slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for torrentFile")
	}

	if len(torrentFileAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// ReloadG refetches the object from the database using the primary keys.
func (o *TorrentFile) ReloadG(ctx context.Context) error {
	if o == nil {
		return errors.New("models: no TorrentFile provided for reload")
	}

	return o.Reload(ctx, boil.GetContextDB())
}

// ReloadP refetches the object from the database with an executor. Panics on error.
func (o *TorrentFile) ReloadP(ctx context.Context, exec boil.ContextExecutor) {
	if err := o.Reload(ctx, exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadGP refetches the object from the database and panics on error.
func (o *TorrentFile) ReloadGP(ctx context.Context) {
	if err := o.Reload(ctx, boil.GetContextDB()); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *TorrentFile) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindTorrentFile(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *TorrentFileSlice) ReloadAllG(ctx context.Context) error {
	if o == nil {
		return errors.New("models: empty TorrentFileSlice provided for reload all")
	}

	return o.ReloadAll(ctx, boil.GetContextDB())
}

// ReloadAllP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *TorrentFileSlice) ReloadAllP(ctx context.Context, exec boil.ContextExecutor) {
	if err := o.ReloadAll(ctx, exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllGP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *TorrentFileSlice) ReloadAllGP(ctx context.Context) {
	if err := o.ReloadAll(ctx, boil.GetContextDB()); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *TorrentFileSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := TorrentFileSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), torrentFilePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"torrentFile\".* FROM \"torrentFile\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, torrentFilePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in TorrentFileSlice")
	}

	*o = slice

	return nil
}

// TorrentFileExistsG checks if the TorrentFile row exists.
func TorrentFileExistsG(ctx context.Context, iD null.Int64) (bool, error) {
	return TorrentFileExists(ctx, boil.GetContextDB(), iD)
}

// TorrentFileExistsP checks if the TorrentFile row exists. Panics on error.
func TorrentFileExistsP(ctx context.Context, exec boil.ContextExecutor, iD null.Int64) bool {
	e, err := TorrentFileExists(ctx, exec, iD)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// TorrentFileExistsGP checks if the TorrentFile row exists. Panics on error.
func TorrentFileExistsGP(ctx context.Context, iD null.Int64) bool {
	e, err := TorrentFileExists(ctx, boil.GetContextDB(), iD)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// TorrentFileExists checks if the TorrentFile row exists.
func TorrentFileExists(ctx context.Context, exec boil.ContextExecutor, iD null.Int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"torrentFile\" where \"id\"=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if torrentFile exists")
	}

	return exists, nil
}

// Exists checks if the TorrentFile row exists.
func (o *TorrentFile) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return TorrentFileExists(ctx, exec, o.ID)
}
