// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// UserEpisode is an object representing the database table.
type UserEpisode struct {
	UserId    null.Int64 `boil:"userId" json:"userId,omitempty" toml:"userId" yaml:"userId,omitempty"`
	EpisodeId null.Int64 `boil:"episodeId" json:"episodeId,omitempty" toml:"episodeId" yaml:"episodeId,omitempty"`
	IsWatched null.Bool  `boil:"isWatched" json:"isWatched,omitempty" toml:"isWatched" yaml:"isWatched,omitempty"`

	R *userEpisodeR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L userEpisodeL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var UserEpisodeColumns = struct {
	UserId    string
	EpisodeId string
	IsWatched string
}{
	UserId:    "userId",
	EpisodeId: "episodeId",
	IsWatched: "isWatched",
}

var UserEpisodeTableColumns = struct {
	UserId    string
	EpisodeId string
	IsWatched string
}{
	UserId:    "userEpisode.userId",
	EpisodeId: "userEpisode.episodeId",
	IsWatched: "userEpisode.isWatched",
}

// Generated where

var UserEpisodeWhere = struct {
	UserId    whereHelpernull_Int64
	EpisodeId whereHelpernull_Int64
	IsWatched whereHelpernull_Bool
}{
	UserId:    whereHelpernull_Int64{field: "\"userEpisode\".\"userId\""},
	EpisodeId: whereHelpernull_Int64{field: "\"userEpisode\".\"episodeId\""},
	IsWatched: whereHelpernull_Bool{field: "\"userEpisode\".\"isWatched\""},
}

// UserEpisodeRels is where relationship names are stored.
var UserEpisodeRels = struct {
	EpisodeIdEpisode string
	UserIdUser       string
}{
	EpisodeIdEpisode: "EpisodeIdEpisode",
	UserIdUser:       "UserIdUser",
}

// userEpisodeR is where relationships are stored.
type userEpisodeR struct {
	EpisodeIdEpisode *Episode `boil:"EpisodeIdEpisode" json:"EpisodeIdEpisode" toml:"EpisodeIdEpisode" yaml:"EpisodeIdEpisode"`
	UserIdUser       *User    `boil:"UserIdUser" json:"UserIdUser" toml:"UserIdUser" yaml:"UserIdUser"`
}

// NewStruct creates a new relationship struct
func (*userEpisodeR) NewStruct() *userEpisodeR {
	return &userEpisodeR{}
}

func (r *userEpisodeR) GetEpisodeIdEpisode() *Episode {
	if r == nil {
		return nil
	}
	return r.EpisodeIdEpisode
}

func (r *userEpisodeR) GetUserIdUser() *User {
	if r == nil {
		return nil
	}
	return r.UserIdUser
}

// userEpisodeL is where Load methods for each relationship are stored.
type userEpisodeL struct{}

var (
	userEpisodeAllColumns            = []string{"userId", "episodeId", "isWatched"}
	userEpisodeColumnsWithoutDefault = []string{}
	userEpisodeColumnsWithDefault    = []string{"userId", "episodeId", "isWatched"}
	userEpisodePrimaryKeyColumns     = []string{"userId", "episodeId"}
	userEpisodeGeneratedColumns      = []string{}
)

type (
	// UserEpisodeSlice is an alias for a slice of pointers to UserEpisode.
	// This should almost always be used instead of []UserEpisode.
	UserEpisodeSlice []*UserEpisode
	// UserEpisodeHook is the signature for custom UserEpisode hook methods
	UserEpisodeHook func(context.Context, boil.ContextExecutor, *UserEpisode) error

	userEpisodeQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	userEpisodeType                 = reflect.TypeOf(&UserEpisode{})
	userEpisodeMapping              = queries.MakeStructMapping(userEpisodeType)
	userEpisodePrimaryKeyMapping, _ = queries.BindMapping(userEpisodeType, userEpisodeMapping, userEpisodePrimaryKeyColumns)
	userEpisodeInsertCacheMut       sync.RWMutex
	userEpisodeInsertCache          = make(map[string]insertCache)
	userEpisodeUpdateCacheMut       sync.RWMutex
	userEpisodeUpdateCache          = make(map[string]updateCache)
	userEpisodeUpsertCacheMut       sync.RWMutex
	userEpisodeUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var userEpisodeAfterSelectMu sync.Mutex
var userEpisodeAfterSelectHooks []UserEpisodeHook

var userEpisodeBeforeInsertMu sync.Mutex
var userEpisodeBeforeInsertHooks []UserEpisodeHook
var userEpisodeAfterInsertMu sync.Mutex
var userEpisodeAfterInsertHooks []UserEpisodeHook

var userEpisodeBeforeUpdateMu sync.Mutex
var userEpisodeBeforeUpdateHooks []UserEpisodeHook
var userEpisodeAfterUpdateMu sync.Mutex
var userEpisodeAfterUpdateHooks []UserEpisodeHook

var userEpisodeBeforeDeleteMu sync.Mutex
var userEpisodeBeforeDeleteHooks []UserEpisodeHook
var userEpisodeAfterDeleteMu sync.Mutex
var userEpisodeAfterDeleteHooks []UserEpisodeHook

var userEpisodeBeforeUpsertMu sync.Mutex
var userEpisodeBeforeUpsertHooks []UserEpisodeHook
var userEpisodeAfterUpsertMu sync.Mutex
var userEpisodeAfterUpsertHooks []UserEpisodeHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *UserEpisode) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userEpisodeAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *UserEpisode) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userEpisodeBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *UserEpisode) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userEpisodeAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *UserEpisode) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userEpisodeBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *UserEpisode) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userEpisodeAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *UserEpisode) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userEpisodeBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *UserEpisode) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userEpisodeAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *UserEpisode) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userEpisodeBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *UserEpisode) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userEpisodeAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddUserEpisodeHook registers your hook function for all future operations.
func AddUserEpisodeHook(hookPoint boil.HookPoint, userEpisodeHook UserEpisodeHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		userEpisodeAfterSelectMu.Lock()
		userEpisodeAfterSelectHooks = append(userEpisodeAfterSelectHooks, userEpisodeHook)
		userEpisodeAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		userEpisodeBeforeInsertMu.Lock()
		userEpisodeBeforeInsertHooks = append(userEpisodeBeforeInsertHooks, userEpisodeHook)
		userEpisodeBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		userEpisodeAfterInsertMu.Lock()
		userEpisodeAfterInsertHooks = append(userEpisodeAfterInsertHooks, userEpisodeHook)
		userEpisodeAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		userEpisodeBeforeUpdateMu.Lock()
		userEpisodeBeforeUpdateHooks = append(userEpisodeBeforeUpdateHooks, userEpisodeHook)
		userEpisodeBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		userEpisodeAfterUpdateMu.Lock()
		userEpisodeAfterUpdateHooks = append(userEpisodeAfterUpdateHooks, userEpisodeHook)
		userEpisodeAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		userEpisodeBeforeDeleteMu.Lock()
		userEpisodeBeforeDeleteHooks = append(userEpisodeBeforeDeleteHooks, userEpisodeHook)
		userEpisodeBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		userEpisodeAfterDeleteMu.Lock()
		userEpisodeAfterDeleteHooks = append(userEpisodeAfterDeleteHooks, userEpisodeHook)
		userEpisodeAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		userEpisodeBeforeUpsertMu.Lock()
		userEpisodeBeforeUpsertHooks = append(userEpisodeBeforeUpsertHooks, userEpisodeHook)
		userEpisodeBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		userEpisodeAfterUpsertMu.Lock()
		userEpisodeAfterUpsertHooks = append(userEpisodeAfterUpsertHooks, userEpisodeHook)
		userEpisodeAfterUpsertMu.Unlock()
	}
}

// One returns a single userEpisode record from the query.
func (q userEpisodeQuery) One(ctx context.Context, exec boil.ContextExecutor) (*UserEpisode, error) {
	o := &UserEpisode{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for userEpisode")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all UserEpisode records from the query.
func (q userEpisodeQuery) All(ctx context.Context, exec boil.ContextExecutor) (UserEpisodeSlice, error) {
	var o []*UserEpisode

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to UserEpisode slice")
	}

	if len(userEpisodeAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all UserEpisode records in the query.
func (q userEpisodeQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count userEpisode rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q userEpisodeQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if userEpisode exists")
	}

	return count > 0, nil
}

// EpisodeIdEpisode pointed to by the foreign key.
func (o *UserEpisode) EpisodeIdEpisode(mods ...qm.QueryMod) episodeQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.EpisodeId),
	}

	queryMods = append(queryMods, mods...)

	return Episodes(queryMods...)
}

// UserIdUser pointed to by the foreign key.
func (o *UserEpisode) UserIdUser(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.UserId),
	}

	queryMods = append(queryMods, mods...)

	return Users(queryMods...)
}

// LoadEpisodeIdEpisode allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (userEpisodeL) LoadEpisodeIdEpisode(ctx context.Context, e boil.ContextExecutor, singular bool, maybeUserEpisode interface{}, mods queries.Applicator) error {
	var slice []*UserEpisode
	var object *UserEpisode

	if singular {
		var ok bool
		object, ok = maybeUserEpisode.(*UserEpisode)
		if !ok {
			object = new(UserEpisode)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeUserEpisode)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeUserEpisode))
			}
		}
	} else {
		s, ok := maybeUserEpisode.(*[]*UserEpisode)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeUserEpisode)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeUserEpisode))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &userEpisodeR{}
		}
		if !queries.IsNil(object.EpisodeId) {
			args[object.EpisodeId] = struct{}{}
		}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &userEpisodeR{}
			}

			if !queries.IsNil(obj.EpisodeId) {
				args[obj.EpisodeId] = struct{}{}
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`episode`),
		qm.WhereIn(`episode.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Episode")
	}

	var resultSlice []*Episode
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Episode")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for episode")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for episode")
	}

	if len(episodeAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.EpisodeIdEpisode = foreign
		if foreign.R == nil {
			foreign.R = &episodeR{}
		}
		foreign.R.EpisodeIdUserEpisodes = append(foreign.R.EpisodeIdUserEpisodes, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.EpisodeId, foreign.ID) {
				local.R.EpisodeIdEpisode = foreign
				if foreign.R == nil {
					foreign.R = &episodeR{}
				}
				foreign.R.EpisodeIdUserEpisodes = append(foreign.R.EpisodeIdUserEpisodes, local)
				break
			}
		}
	}

	return nil
}

// LoadUserIdUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (userEpisodeL) LoadUserIdUser(ctx context.Context, e boil.ContextExecutor, singular bool, maybeUserEpisode interface{}, mods queries.Applicator) error {
	var slice []*UserEpisode
	var object *UserEpisode

	if singular {
		var ok bool
		object, ok = maybeUserEpisode.(*UserEpisode)
		if !ok {
			object = new(UserEpisode)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeUserEpisode)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeUserEpisode))
			}
		}
	} else {
		s, ok := maybeUserEpisode.(*[]*UserEpisode)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeUserEpisode)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeUserEpisode))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &userEpisodeR{}
		}
		if !queries.IsNil(object.UserId) {
			args[object.UserId] = struct{}{}
		}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &userEpisodeR{}
			}

			if !queries.IsNil(obj.UserId) {
				args[obj.UserId] = struct{}{}
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`user`),
		qm.WhereIn(`user.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for user")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for user")
	}

	if len(userAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.UserIdUser = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.UserIdUserEpisodes = append(foreign.R.UserIdUserEpisodes, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.UserId, foreign.ID) {
				local.R.UserIdUser = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.UserIdUserEpisodes = append(foreign.R.UserIdUserEpisodes, local)
				break
			}
		}
	}

	return nil
}

// SetEpisodeIdEpisode of the userEpisode to the related item.
// Sets o.R.EpisodeIdEpisode to related.
// Adds o to related.R.EpisodeIdUserEpisodes.
func (o *UserEpisode) SetEpisodeIdEpisode(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Episode) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"userEpisode\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 0, []string{"episodeId"}),
		strmangle.WhereClause("\"", "\"", 0, userEpisodePrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.UserId, o.EpisodeId}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.EpisodeId, related.ID)
	if o.R == nil {
		o.R = &userEpisodeR{
			EpisodeIdEpisode: related,
		}
	} else {
		o.R.EpisodeIdEpisode = related
	}

	if related.R == nil {
		related.R = &episodeR{
			EpisodeIdUserEpisodes: UserEpisodeSlice{o},
		}
	} else {
		related.R.EpisodeIdUserEpisodes = append(related.R.EpisodeIdUserEpisodes, o)
	}

	return nil
}

// RemoveEpisodeIdEpisode relationship.
// Sets o.R.EpisodeIdEpisode to nil.
// Removes o from all passed in related items' relationships struct.
func (o *UserEpisode) RemoveEpisodeIdEpisode(ctx context.Context, exec boil.ContextExecutor, related *Episode) error {
	var err error

	queries.SetScanner(&o.EpisodeId, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("episodeId")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.EpisodeIdEpisode = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.EpisodeIdUserEpisodes {
		if queries.Equal(o.EpisodeId, ri.EpisodeId) {
			continue
		}

		ln := len(related.R.EpisodeIdUserEpisodes)
		if ln > 1 && i < ln-1 {
			related.R.EpisodeIdUserEpisodes[i] = related.R.EpisodeIdUserEpisodes[ln-1]
		}
		related.R.EpisodeIdUserEpisodes = related.R.EpisodeIdUserEpisodes[:ln-1]
		break
	}
	return nil
}

// SetUserIdUser of the userEpisode to the related item.
// Sets o.R.UserIdUser to related.
// Adds o to related.R.UserIdUserEpisodes.
func (o *UserEpisode) SetUserIdUser(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"userEpisode\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 0, []string{"userId"}),
		strmangle.WhereClause("\"", "\"", 0, userEpisodePrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.UserId, o.EpisodeId}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.UserId, related.ID)
	if o.R == nil {
		o.R = &userEpisodeR{
			UserIdUser: related,
		}
	} else {
		o.R.UserIdUser = related
	}

	if related.R == nil {
		related.R = &userR{
			UserIdUserEpisodes: UserEpisodeSlice{o},
		}
	} else {
		related.R.UserIdUserEpisodes = append(related.R.UserIdUserEpisodes, o)
	}

	return nil
}

// RemoveUserIdUser relationship.
// Sets o.R.UserIdUser to nil.
// Removes o from all passed in related items' relationships struct.
func (o *UserEpisode) RemoveUserIdUser(ctx context.Context, exec boil.ContextExecutor, related *User) error {
	var err error

	queries.SetScanner(&o.UserId, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("userId")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.UserIdUser = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.UserIdUserEpisodes {
		if queries.Equal(o.UserId, ri.UserId) {
			continue
		}

		ln := len(related.R.UserIdUserEpisodes)
		if ln > 1 && i < ln-1 {
			related.R.UserIdUserEpisodes[i] = related.R.UserIdUserEpisodes[ln-1]
		}
		related.R.UserIdUserEpisodes = related.R.UserIdUserEpisodes[:ln-1]
		break
	}
	return nil
}

// UserEpisodes retrieves all the records using an executor.
func UserEpisodes(mods ...qm.QueryMod) userEpisodeQuery {
	mods = append(mods, qm.From("\"userEpisode\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"userEpisode\".*"})
	}

	return userEpisodeQuery{q}
}

// FindUserEpisode retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindUserEpisode(ctx context.Context, exec boil.ContextExecutor, userId null.Int64, episodeId null.Int64, selectCols ...string) (*UserEpisode, error) {
	userEpisodeObj := &UserEpisode{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"userEpisode\" where \"userId\"=? AND \"episodeId\"=?", sel,
	)

	q := queries.Raw(query, userId, episodeId)

	err := q.Bind(ctx, exec, userEpisodeObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from userEpisode")
	}

	if err = userEpisodeObj.doAfterSelectHooks(ctx, exec); err != nil {
		return userEpisodeObj, err
	}

	return userEpisodeObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *UserEpisode) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no userEpisode provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(userEpisodeColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	userEpisodeInsertCacheMut.RLock()
	cache, cached := userEpisodeInsertCache[key]
	userEpisodeInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			userEpisodeAllColumns,
			userEpisodeColumnsWithDefault,
			userEpisodeColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(userEpisodeType, userEpisodeMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(userEpisodeType, userEpisodeMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"userEpisode\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"userEpisode\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into userEpisode")
	}

	if !cached {
		userEpisodeInsertCacheMut.Lock()
		userEpisodeInsertCache[key] = cache
		userEpisodeInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the UserEpisode.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *UserEpisode) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	userEpisodeUpdateCacheMut.RLock()
	cache, cached := userEpisodeUpdateCache[key]
	userEpisodeUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			userEpisodeAllColumns,
			userEpisodePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update userEpisode, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"userEpisode\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 0, wl),
			strmangle.WhereClause("\"", "\"", 0, userEpisodePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(userEpisodeType, userEpisodeMapping, append(wl, userEpisodePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update userEpisode row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for userEpisode")
	}

	if !cached {
		userEpisodeUpdateCacheMut.Lock()
		userEpisodeUpdateCache[key] = cache
		userEpisodeUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q userEpisodeQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for userEpisode")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for userEpisode")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o UserEpisodeSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userEpisodePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"userEpisode\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, userEpisodePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in userEpisode slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all userEpisode")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *UserEpisode) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no userEpisode provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(userEpisodeColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	userEpisodeUpsertCacheMut.RLock()
	cache, cached := userEpisodeUpsertCache[key]
	userEpisodeUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			userEpisodeAllColumns,
			userEpisodeColumnsWithDefault,
			userEpisodeColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			userEpisodeAllColumns,
			userEpisodePrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert userEpisode, could not build update column list")
		}

		ret := strmangle.SetComplement(userEpisodeAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(userEpisodePrimaryKeyColumns))
			copy(conflict, userEpisodePrimaryKeyColumns)
		}
		cache.query = buildUpsertQuerySQLite(dialect, "\"userEpisode\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(userEpisodeType, userEpisodeMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(userEpisodeType, userEpisodeMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert userEpisode")
	}

	if !cached {
		userEpisodeUpsertCacheMut.Lock()
		userEpisodeUpsertCache[key] = cache
		userEpisodeUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single UserEpisode record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *UserEpisode) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no UserEpisode provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), userEpisodePrimaryKeyMapping)
	sql := "DELETE FROM \"userEpisode\" WHERE \"userId\"=? AND \"episodeId\"=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from userEpisode")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for userEpisode")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q userEpisodeQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no userEpisodeQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from userEpisode")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for userEpisode")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o UserEpisodeSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(userEpisodeBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userEpisodePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"userEpisode\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, userEpisodePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from userEpisode slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for userEpisode")
	}

	if len(userEpisodeAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *UserEpisode) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindUserEpisode(ctx, exec, o.UserId, o.EpisodeId)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *UserEpisodeSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := UserEpisodeSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userEpisodePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"userEpisode\".* FROM \"userEpisode\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, userEpisodePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in UserEpisodeSlice")
	}

	*o = slice

	return nil
}

// UserEpisodeExists checks if the UserEpisode row exists.
func UserEpisodeExists(ctx context.Context, exec boil.ContextExecutor, userId null.Int64, episodeId null.Int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"userEpisode\" where \"userId\"=? AND \"episodeId\"=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, userId, episodeId)
	}
	row := exec.QueryRowContext(ctx, sql, userId, episodeId)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if userEpisode exists")
	}

	return exists, nil
}

// Exists checks if the UserEpisode row exists.
func (o *UserEpisode) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return UserEpisodeExists(ctx, exec, o.UserId, o.EpisodeId)
}
