// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// UserMetaDatum is an object representing the database table.
type UserMetaDatum struct {
	UserId     null.Int64 `boil:"userId" json:"userId,omitempty" toml:"userId" yaml:"userId,omitempty"`
	MetaDataId null.Int64 `boil:"metaDataId" json:"metaDataId,omitempty" toml:"metaDataId" yaml:"metaDataId,omitempty"`
	IsWatched  null.Bool  `boil:"isWatched" json:"isWatched,omitempty" toml:"isWatched" yaml:"isWatched,omitempty"`

	R *userMetaDatumR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L userMetaDatumL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var UserMetaDatumColumns = struct {
	UserId     string
	MetaDataId string
	IsWatched  string
}{
	UserId:     "userId",
	MetaDataId: "metaDataId",
	IsWatched:  "isWatched",
}

var UserMetaDatumTableColumns = struct {
	UserId     string
	MetaDataId string
	IsWatched  string
}{
	UserId:     "userMetaData.userId",
	MetaDataId: "userMetaData.metaDataId",
	IsWatched:  "userMetaData.isWatched",
}

// Generated where

var UserMetaDatumWhere = struct {
	UserId     whereHelpernull_Int64
	MetaDataId whereHelpernull_Int64
	IsWatched  whereHelpernull_Bool
}{
	UserId:     whereHelpernull_Int64{field: "\"userMetaData\".\"userId\""},
	MetaDataId: whereHelpernull_Int64{field: "\"userMetaData\".\"metaDataId\""},
	IsWatched:  whereHelpernull_Bool{field: "\"userMetaData\".\"isWatched\""},
}

// UserMetaDatumRels is where relationship names are stored.
var UserMetaDatumRels = struct {
	MetaDataIdMetaDatum string
	UserIdUser          string
}{
	MetaDataIdMetaDatum: "MetaDataIdMetaDatum",
	UserIdUser:          "UserIdUser",
}

// userMetaDatumR is where relationships are stored.
type userMetaDatumR struct {
	MetaDataIdMetaDatum *MetaDatum `boil:"MetaDataIdMetaDatum" json:"MetaDataIdMetaDatum" toml:"MetaDataIdMetaDatum" yaml:"MetaDataIdMetaDatum"`
	UserIdUser          *User      `boil:"UserIdUser" json:"UserIdUser" toml:"UserIdUser" yaml:"UserIdUser"`
}

// NewStruct creates a new relationship struct
func (*userMetaDatumR) NewStruct() *userMetaDatumR {
	return &userMetaDatumR{}
}

func (r *userMetaDatumR) GetMetaDataIdMetaDatum() *MetaDatum {
	if r == nil {
		return nil
	}
	return r.MetaDataIdMetaDatum
}

func (r *userMetaDatumR) GetUserIdUser() *User {
	if r == nil {
		return nil
	}
	return r.UserIdUser
}

// userMetaDatumL is where Load methods for each relationship are stored.
type userMetaDatumL struct{}

var (
	userMetaDatumAllColumns            = []string{"userId", "metaDataId", "isWatched"}
	userMetaDatumColumnsWithoutDefault = []string{}
	userMetaDatumColumnsWithDefault    = []string{"userId", "metaDataId", "isWatched"}
	userMetaDatumPrimaryKeyColumns     = []string{"userId", "metaDataId"}
	userMetaDatumGeneratedColumns      = []string{}
)

type (
	// UserMetaDatumSlice is an alias for a slice of pointers to UserMetaDatum.
	// This should almost always be used instead of []UserMetaDatum.
	UserMetaDatumSlice []*UserMetaDatum
	// UserMetaDatumHook is the signature for custom UserMetaDatum hook methods
	UserMetaDatumHook func(context.Context, boil.ContextExecutor, *UserMetaDatum) error

	userMetaDatumQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	userMetaDatumType                 = reflect.TypeOf(&UserMetaDatum{})
	userMetaDatumMapping              = queries.MakeStructMapping(userMetaDatumType)
	userMetaDatumPrimaryKeyMapping, _ = queries.BindMapping(userMetaDatumType, userMetaDatumMapping, userMetaDatumPrimaryKeyColumns)
	userMetaDatumInsertCacheMut       sync.RWMutex
	userMetaDatumInsertCache          = make(map[string]insertCache)
	userMetaDatumUpdateCacheMut       sync.RWMutex
	userMetaDatumUpdateCache          = make(map[string]updateCache)
	userMetaDatumUpsertCacheMut       sync.RWMutex
	userMetaDatumUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var userMetaDatumAfterSelectMu sync.Mutex
var userMetaDatumAfterSelectHooks []UserMetaDatumHook

var userMetaDatumBeforeInsertMu sync.Mutex
var userMetaDatumBeforeInsertHooks []UserMetaDatumHook
var userMetaDatumAfterInsertMu sync.Mutex
var userMetaDatumAfterInsertHooks []UserMetaDatumHook

var userMetaDatumBeforeUpdateMu sync.Mutex
var userMetaDatumBeforeUpdateHooks []UserMetaDatumHook
var userMetaDatumAfterUpdateMu sync.Mutex
var userMetaDatumAfterUpdateHooks []UserMetaDatumHook

var userMetaDatumBeforeDeleteMu sync.Mutex
var userMetaDatumBeforeDeleteHooks []UserMetaDatumHook
var userMetaDatumAfterDeleteMu sync.Mutex
var userMetaDatumAfterDeleteHooks []UserMetaDatumHook

var userMetaDatumBeforeUpsertMu sync.Mutex
var userMetaDatumBeforeUpsertHooks []UserMetaDatumHook
var userMetaDatumAfterUpsertMu sync.Mutex
var userMetaDatumAfterUpsertHooks []UserMetaDatumHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *UserMetaDatum) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userMetaDatumAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *UserMetaDatum) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userMetaDatumBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *UserMetaDatum) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userMetaDatumAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *UserMetaDatum) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userMetaDatumBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *UserMetaDatum) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userMetaDatumAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *UserMetaDatum) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userMetaDatumBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *UserMetaDatum) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userMetaDatumAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *UserMetaDatum) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userMetaDatumBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *UserMetaDatum) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userMetaDatumAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddUserMetaDatumHook registers your hook function for all future operations.
func AddUserMetaDatumHook(hookPoint boil.HookPoint, userMetaDatumHook UserMetaDatumHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		userMetaDatumAfterSelectMu.Lock()
		userMetaDatumAfterSelectHooks = append(userMetaDatumAfterSelectHooks, userMetaDatumHook)
		userMetaDatumAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		userMetaDatumBeforeInsertMu.Lock()
		userMetaDatumBeforeInsertHooks = append(userMetaDatumBeforeInsertHooks, userMetaDatumHook)
		userMetaDatumBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		userMetaDatumAfterInsertMu.Lock()
		userMetaDatumAfterInsertHooks = append(userMetaDatumAfterInsertHooks, userMetaDatumHook)
		userMetaDatumAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		userMetaDatumBeforeUpdateMu.Lock()
		userMetaDatumBeforeUpdateHooks = append(userMetaDatumBeforeUpdateHooks, userMetaDatumHook)
		userMetaDatumBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		userMetaDatumAfterUpdateMu.Lock()
		userMetaDatumAfterUpdateHooks = append(userMetaDatumAfterUpdateHooks, userMetaDatumHook)
		userMetaDatumAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		userMetaDatumBeforeDeleteMu.Lock()
		userMetaDatumBeforeDeleteHooks = append(userMetaDatumBeforeDeleteHooks, userMetaDatumHook)
		userMetaDatumBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		userMetaDatumAfterDeleteMu.Lock()
		userMetaDatumAfterDeleteHooks = append(userMetaDatumAfterDeleteHooks, userMetaDatumHook)
		userMetaDatumAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		userMetaDatumBeforeUpsertMu.Lock()
		userMetaDatumBeforeUpsertHooks = append(userMetaDatumBeforeUpsertHooks, userMetaDatumHook)
		userMetaDatumBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		userMetaDatumAfterUpsertMu.Lock()
		userMetaDatumAfterUpsertHooks = append(userMetaDatumAfterUpsertHooks, userMetaDatumHook)
		userMetaDatumAfterUpsertMu.Unlock()
	}
}

// One returns a single userMetaDatum record from the query.
func (q userMetaDatumQuery) One(ctx context.Context, exec boil.ContextExecutor) (*UserMetaDatum, error) {
	o := &UserMetaDatum{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for userMetaData")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all UserMetaDatum records from the query.
func (q userMetaDatumQuery) All(ctx context.Context, exec boil.ContextExecutor) (UserMetaDatumSlice, error) {
	var o []*UserMetaDatum

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to UserMetaDatum slice")
	}

	if len(userMetaDatumAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all UserMetaDatum records in the query.
func (q userMetaDatumQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count userMetaData rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q userMetaDatumQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if userMetaData exists")
	}

	return count > 0, nil
}

// MetaDataIdMetaDatum pointed to by the foreign key.
func (o *UserMetaDatum) MetaDataIdMetaDatum(mods ...qm.QueryMod) metaDatumQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.MetaDataId),
	}

	queryMods = append(queryMods, mods...)

	return MetaData(queryMods...)
}

// UserIdUser pointed to by the foreign key.
func (o *UserMetaDatum) UserIdUser(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.UserId),
	}

	queryMods = append(queryMods, mods...)

	return Users(queryMods...)
}

// LoadMetaDataIdMetaDatum allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (userMetaDatumL) LoadMetaDataIdMetaDatum(ctx context.Context, e boil.ContextExecutor, singular bool, maybeUserMetaDatum interface{}, mods queries.Applicator) error {
	var slice []*UserMetaDatum
	var object *UserMetaDatum

	if singular {
		var ok bool
		object, ok = maybeUserMetaDatum.(*UserMetaDatum)
		if !ok {
			object = new(UserMetaDatum)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeUserMetaDatum)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeUserMetaDatum))
			}
		}
	} else {
		s, ok := maybeUserMetaDatum.(*[]*UserMetaDatum)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeUserMetaDatum)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeUserMetaDatum))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &userMetaDatumR{}
		}
		if !queries.IsNil(object.MetaDataId) {
			args[object.MetaDataId] = struct{}{}
		}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &userMetaDatumR{}
			}

			if !queries.IsNil(obj.MetaDataId) {
				args[obj.MetaDataId] = struct{}{}
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`metaData`),
		qm.WhereIn(`metaData.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load MetaDatum")
	}

	var resultSlice []*MetaDatum
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice MetaDatum")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for metaData")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for metaData")
	}

	if len(metaDatumAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.MetaDataIdMetaDatum = foreign
		if foreign.R == nil {
			foreign.R = &metaDatumR{}
		}
		foreign.R.MetaDataIdUserMetaData = append(foreign.R.MetaDataIdUserMetaData, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.MetaDataId, foreign.ID) {
				local.R.MetaDataIdMetaDatum = foreign
				if foreign.R == nil {
					foreign.R = &metaDatumR{}
				}
				foreign.R.MetaDataIdUserMetaData = append(foreign.R.MetaDataIdUserMetaData, local)
				break
			}
		}
	}

	return nil
}

// LoadUserIdUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (userMetaDatumL) LoadUserIdUser(ctx context.Context, e boil.ContextExecutor, singular bool, maybeUserMetaDatum interface{}, mods queries.Applicator) error {
	var slice []*UserMetaDatum
	var object *UserMetaDatum

	if singular {
		var ok bool
		object, ok = maybeUserMetaDatum.(*UserMetaDatum)
		if !ok {
			object = new(UserMetaDatum)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeUserMetaDatum)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeUserMetaDatum))
			}
		}
	} else {
		s, ok := maybeUserMetaDatum.(*[]*UserMetaDatum)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeUserMetaDatum)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeUserMetaDatum))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &userMetaDatumR{}
		}
		if !queries.IsNil(object.UserId) {
			args[object.UserId] = struct{}{}
		}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &userMetaDatumR{}
			}

			if !queries.IsNil(obj.UserId) {
				args[obj.UserId] = struct{}{}
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`user`),
		qm.WhereIn(`user.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for user")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for user")
	}

	if len(userAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.UserIdUser = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.UserIdUserMetaData = append(foreign.R.UserIdUserMetaData, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.UserId, foreign.ID) {
				local.R.UserIdUser = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.UserIdUserMetaData = append(foreign.R.UserIdUserMetaData, local)
				break
			}
		}
	}

	return nil
}

// SetMetaDataIdMetaDatum of the userMetaDatum to the related item.
// Sets o.R.MetaDataIdMetaDatum to related.
// Adds o to related.R.MetaDataIdUserMetaData.
func (o *UserMetaDatum) SetMetaDataIdMetaDatum(ctx context.Context, exec boil.ContextExecutor, insert bool, related *MetaDatum) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"userMetaData\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 0, []string{"metaDataId"}),
		strmangle.WhereClause("\"", "\"", 0, userMetaDatumPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.UserId, o.MetaDataId}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.MetaDataId, related.ID)
	if o.R == nil {
		o.R = &userMetaDatumR{
			MetaDataIdMetaDatum: related,
		}
	} else {
		o.R.MetaDataIdMetaDatum = related
	}

	if related.R == nil {
		related.R = &metaDatumR{
			MetaDataIdUserMetaData: UserMetaDatumSlice{o},
		}
	} else {
		related.R.MetaDataIdUserMetaData = append(related.R.MetaDataIdUserMetaData, o)
	}

	return nil
}

// RemoveMetaDataIdMetaDatum relationship.
// Sets o.R.MetaDataIdMetaDatum to nil.
// Removes o from all passed in related items' relationships struct.
func (o *UserMetaDatum) RemoveMetaDataIdMetaDatum(ctx context.Context, exec boil.ContextExecutor, related *MetaDatum) error {
	var err error

	queries.SetScanner(&o.MetaDataId, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("metaDataId")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.MetaDataIdMetaDatum = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.MetaDataIdUserMetaData {
		if queries.Equal(o.MetaDataId, ri.MetaDataId) {
			continue
		}

		ln := len(related.R.MetaDataIdUserMetaData)
		if ln > 1 && i < ln-1 {
			related.R.MetaDataIdUserMetaData[i] = related.R.MetaDataIdUserMetaData[ln-1]
		}
		related.R.MetaDataIdUserMetaData = related.R.MetaDataIdUserMetaData[:ln-1]
		break
	}
	return nil
}

// SetUserIdUser of the userMetaDatum to the related item.
// Sets o.R.UserIdUser to related.
// Adds o to related.R.UserIdUserMetaData.
func (o *UserMetaDatum) SetUserIdUser(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"userMetaData\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 0, []string{"userId"}),
		strmangle.WhereClause("\"", "\"", 0, userMetaDatumPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.UserId, o.MetaDataId}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.UserId, related.ID)
	if o.R == nil {
		o.R = &userMetaDatumR{
			UserIdUser: related,
		}
	} else {
		o.R.UserIdUser = related
	}

	if related.R == nil {
		related.R = &userR{
			UserIdUserMetaData: UserMetaDatumSlice{o},
		}
	} else {
		related.R.UserIdUserMetaData = append(related.R.UserIdUserMetaData, o)
	}

	return nil
}

// RemoveUserIdUser relationship.
// Sets o.R.UserIdUser to nil.
// Removes o from all passed in related items' relationships struct.
func (o *UserMetaDatum) RemoveUserIdUser(ctx context.Context, exec boil.ContextExecutor, related *User) error {
	var err error

	queries.SetScanner(&o.UserId, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("userId")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.UserIdUser = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.UserIdUserMetaData {
		if queries.Equal(o.UserId, ri.UserId) {
			continue
		}

		ln := len(related.R.UserIdUserMetaData)
		if ln > 1 && i < ln-1 {
			related.R.UserIdUserMetaData[i] = related.R.UserIdUserMetaData[ln-1]
		}
		related.R.UserIdUserMetaData = related.R.UserIdUserMetaData[:ln-1]
		break
	}
	return nil
}

// UserMetaData retrieves all the records using an executor.
func UserMetaData(mods ...qm.QueryMod) userMetaDatumQuery {
	mods = append(mods, qm.From("\"userMetaData\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"userMetaData\".*"})
	}

	return userMetaDatumQuery{q}
}

// FindUserMetaDatum retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindUserMetaDatum(ctx context.Context, exec boil.ContextExecutor, userId null.Int64, metaDataId null.Int64, selectCols ...string) (*UserMetaDatum, error) {
	userMetaDatumObj := &UserMetaDatum{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"userMetaData\" where \"userId\"=? AND \"metaDataId\"=?", sel,
	)

	q := queries.Raw(query, userId, metaDataId)

	err := q.Bind(ctx, exec, userMetaDatumObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from userMetaData")
	}

	if err = userMetaDatumObj.doAfterSelectHooks(ctx, exec); err != nil {
		return userMetaDatumObj, err
	}

	return userMetaDatumObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *UserMetaDatum) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no userMetaData provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(userMetaDatumColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	userMetaDatumInsertCacheMut.RLock()
	cache, cached := userMetaDatumInsertCache[key]
	userMetaDatumInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			userMetaDatumAllColumns,
			userMetaDatumColumnsWithDefault,
			userMetaDatumColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(userMetaDatumType, userMetaDatumMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(userMetaDatumType, userMetaDatumMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"userMetaData\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"userMetaData\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into userMetaData")
	}

	if !cached {
		userMetaDatumInsertCacheMut.Lock()
		userMetaDatumInsertCache[key] = cache
		userMetaDatumInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the UserMetaDatum.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *UserMetaDatum) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	userMetaDatumUpdateCacheMut.RLock()
	cache, cached := userMetaDatumUpdateCache[key]
	userMetaDatumUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			userMetaDatumAllColumns,
			userMetaDatumPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update userMetaData, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"userMetaData\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 0, wl),
			strmangle.WhereClause("\"", "\"", 0, userMetaDatumPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(userMetaDatumType, userMetaDatumMapping, append(wl, userMetaDatumPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update userMetaData row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for userMetaData")
	}

	if !cached {
		userMetaDatumUpdateCacheMut.Lock()
		userMetaDatumUpdateCache[key] = cache
		userMetaDatumUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q userMetaDatumQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for userMetaData")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for userMetaData")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o UserMetaDatumSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userMetaDatumPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"userMetaData\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, userMetaDatumPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in userMetaDatum slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all userMetaDatum")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *UserMetaDatum) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no userMetaData provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(userMetaDatumColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	userMetaDatumUpsertCacheMut.RLock()
	cache, cached := userMetaDatumUpsertCache[key]
	userMetaDatumUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			userMetaDatumAllColumns,
			userMetaDatumColumnsWithDefault,
			userMetaDatumColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			userMetaDatumAllColumns,
			userMetaDatumPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert userMetaData, could not build update column list")
		}

		ret := strmangle.SetComplement(userMetaDatumAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(userMetaDatumPrimaryKeyColumns))
			copy(conflict, userMetaDatumPrimaryKeyColumns)
		}
		cache.query = buildUpsertQuerySQLite(dialect, "\"userMetaData\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(userMetaDatumType, userMetaDatumMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(userMetaDatumType, userMetaDatumMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert userMetaData")
	}

	if !cached {
		userMetaDatumUpsertCacheMut.Lock()
		userMetaDatumUpsertCache[key] = cache
		userMetaDatumUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single UserMetaDatum record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *UserMetaDatum) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no UserMetaDatum provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), userMetaDatumPrimaryKeyMapping)
	sql := "DELETE FROM \"userMetaData\" WHERE \"userId\"=? AND \"metaDataId\"=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from userMetaData")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for userMetaData")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q userMetaDatumQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no userMetaDatumQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from userMetaData")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for userMetaData")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o UserMetaDatumSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(userMetaDatumBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userMetaDatumPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"userMetaData\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, userMetaDatumPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from userMetaDatum slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for userMetaData")
	}

	if len(userMetaDatumAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *UserMetaDatum) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindUserMetaDatum(ctx, exec, o.UserId, o.MetaDataId)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *UserMetaDatumSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := UserMetaDatumSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userMetaDatumPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"userMetaData\".* FROM \"userMetaData\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, userMetaDatumPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in UserMetaDatumSlice")
	}

	*o = slice

	return nil
}

// UserMetaDatumExists checks if the UserMetaDatum row exists.
func UserMetaDatumExists(ctx context.Context, exec boil.ContextExecutor, userId null.Int64, metaDataId null.Int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"userMetaData\" where \"userId\"=? AND \"metaDataId\"=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, userId, metaDataId)
	}
	row := exec.QueryRowContext(ctx, sql, userId, metaDataId)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if userMetaData exists")
	}

	return exists, nil
}

// Exists checks if the UserMetaDatum row exists.
func (o *UserMetaDatum) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return UserMetaDatumExists(ctx, exec, o.UserId, o.MetaDataId)
}
