// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testUserMetaData(t *testing.T) {
	t.Parallel()

	query := UserMetaData()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testUserMetaDataDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserMetaDatum{}
	if err = randomize.Struct(seed, o, userMetaDatumDBTypes, true, userMetaDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserMetaDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := UserMetaData().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testUserMetaDataQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserMetaDatum{}
	if err = randomize.Struct(seed, o, userMetaDatumDBTypes, true, userMetaDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserMetaDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := UserMetaData().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := UserMetaData().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testUserMetaDataSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserMetaDatum{}
	if err = randomize.Struct(seed, o, userMetaDatumDBTypes, true, userMetaDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserMetaDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := UserMetaDatumSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := UserMetaData().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testUserMetaDataExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserMetaDatum{}
	if err = randomize.Struct(seed, o, userMetaDatumDBTypes, true, userMetaDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserMetaDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := UserMetaDatumExists(ctx, tx, o.UserId, o.MetaDataId)
	if err != nil {
		t.Errorf("Unable to check if UserMetaDatum exists: %s", err)
	}
	if !e {
		t.Errorf("Expected UserMetaDatumExists to return true, but got false.")
	}
}

func testUserMetaDataFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserMetaDatum{}
	if err = randomize.Struct(seed, o, userMetaDatumDBTypes, true, userMetaDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserMetaDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	userMetaDatumFound, err := FindUserMetaDatum(ctx, tx, o.UserId, o.MetaDataId)
	if err != nil {
		t.Error(err)
	}

	if userMetaDatumFound == nil {
		t.Error("want a record, got nil")
	}
}

func testUserMetaDataBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserMetaDatum{}
	if err = randomize.Struct(seed, o, userMetaDatumDBTypes, true, userMetaDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserMetaDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = UserMetaData().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testUserMetaDataOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserMetaDatum{}
	if err = randomize.Struct(seed, o, userMetaDatumDBTypes, true, userMetaDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserMetaDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := UserMetaData().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testUserMetaDataAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	userMetaDatumOne := &UserMetaDatum{}
	userMetaDatumTwo := &UserMetaDatum{}
	if err = randomize.Struct(seed, userMetaDatumOne, userMetaDatumDBTypes, false, userMetaDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserMetaDatum struct: %s", err)
	}
	if err = randomize.Struct(seed, userMetaDatumTwo, userMetaDatumDBTypes, false, userMetaDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserMetaDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = userMetaDatumOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = userMetaDatumTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := UserMetaData().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testUserMetaDataCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	userMetaDatumOne := &UserMetaDatum{}
	userMetaDatumTwo := &UserMetaDatum{}
	if err = randomize.Struct(seed, userMetaDatumOne, userMetaDatumDBTypes, false, userMetaDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserMetaDatum struct: %s", err)
	}
	if err = randomize.Struct(seed, userMetaDatumTwo, userMetaDatumDBTypes, false, userMetaDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserMetaDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = userMetaDatumOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = userMetaDatumTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := UserMetaData().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func userMetaDatumBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *UserMetaDatum) error {
	*o = UserMetaDatum{}
	return nil
}

func userMetaDatumAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *UserMetaDatum) error {
	*o = UserMetaDatum{}
	return nil
}

func userMetaDatumAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *UserMetaDatum) error {
	*o = UserMetaDatum{}
	return nil
}

func userMetaDatumBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *UserMetaDatum) error {
	*o = UserMetaDatum{}
	return nil
}

func userMetaDatumAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *UserMetaDatum) error {
	*o = UserMetaDatum{}
	return nil
}

func userMetaDatumBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *UserMetaDatum) error {
	*o = UserMetaDatum{}
	return nil
}

func userMetaDatumAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *UserMetaDatum) error {
	*o = UserMetaDatum{}
	return nil
}

func userMetaDatumBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *UserMetaDatum) error {
	*o = UserMetaDatum{}
	return nil
}

func userMetaDatumAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *UserMetaDatum) error {
	*o = UserMetaDatum{}
	return nil
}

func testUserMetaDataHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &UserMetaDatum{}
	o := &UserMetaDatum{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, userMetaDatumDBTypes, false); err != nil {
		t.Errorf("Unable to randomize UserMetaDatum object: %s", err)
	}

	AddUserMetaDatumHook(boil.BeforeInsertHook, userMetaDatumBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	userMetaDatumBeforeInsertHooks = []UserMetaDatumHook{}

	AddUserMetaDatumHook(boil.AfterInsertHook, userMetaDatumAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	userMetaDatumAfterInsertHooks = []UserMetaDatumHook{}

	AddUserMetaDatumHook(boil.AfterSelectHook, userMetaDatumAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	userMetaDatumAfterSelectHooks = []UserMetaDatumHook{}

	AddUserMetaDatumHook(boil.BeforeUpdateHook, userMetaDatumBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	userMetaDatumBeforeUpdateHooks = []UserMetaDatumHook{}

	AddUserMetaDatumHook(boil.AfterUpdateHook, userMetaDatumAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	userMetaDatumAfterUpdateHooks = []UserMetaDatumHook{}

	AddUserMetaDatumHook(boil.BeforeDeleteHook, userMetaDatumBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	userMetaDatumBeforeDeleteHooks = []UserMetaDatumHook{}

	AddUserMetaDatumHook(boil.AfterDeleteHook, userMetaDatumAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	userMetaDatumAfterDeleteHooks = []UserMetaDatumHook{}

	AddUserMetaDatumHook(boil.BeforeUpsertHook, userMetaDatumBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	userMetaDatumBeforeUpsertHooks = []UserMetaDatumHook{}

	AddUserMetaDatumHook(boil.AfterUpsertHook, userMetaDatumAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	userMetaDatumAfterUpsertHooks = []UserMetaDatumHook{}
}

func testUserMetaDataInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserMetaDatum{}
	if err = randomize.Struct(seed, o, userMetaDatumDBTypes, true, userMetaDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserMetaDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := UserMetaData().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testUserMetaDataInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserMetaDatum{}
	if err = randomize.Struct(seed, o, userMetaDatumDBTypes, true); err != nil {
		t.Errorf("Unable to randomize UserMetaDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(userMetaDatumColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := UserMetaData().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testUserMetaDatumToOneMetaDatumUsingMetaDataIdMetaDatum(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local UserMetaDatum
	var foreign MetaDatum

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, userMetaDatumDBTypes, true, userMetaDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserMetaDatum struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, metaDatumDBTypes, true, metaDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MetaDatum struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&local.MetaDataId, foreign.ID)
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.MetaDataIdMetaDatum().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if !queries.Equal(check.ID, foreign.ID) {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	ranAfterSelectHook := false
	AddMetaDatumHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *MetaDatum) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := UserMetaDatumSlice{&local}
	if err = local.L.LoadMetaDataIdMetaDatum(ctx, tx, false, (*[]*UserMetaDatum)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.MetaDataIdMetaDatum == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.MetaDataIdMetaDatum = nil
	if err = local.L.LoadMetaDataIdMetaDatum(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.MetaDataIdMetaDatum == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testUserMetaDatumToOneUserUsingUserIdUser(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local UserMetaDatum
	var foreign User

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, userMetaDatumDBTypes, true, userMetaDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserMetaDatum struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, userDBTypes, true, userColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize User struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&local.UserId, foreign.ID)
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.UserIdUser().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if !queries.Equal(check.ID, foreign.ID) {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	ranAfterSelectHook := false
	AddUserHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *User) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := UserMetaDatumSlice{&local}
	if err = local.L.LoadUserIdUser(ctx, tx, false, (*[]*UserMetaDatum)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.UserIdUser == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.UserIdUser = nil
	if err = local.L.LoadUserIdUser(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.UserIdUser == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testUserMetaDatumToOneSetOpMetaDatumUsingMetaDataIdMetaDatum(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a UserMetaDatum
	var b, c MetaDatum

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, userMetaDatumDBTypes, false, strmangle.SetComplement(userMetaDatumPrimaryKeyColumns, userMetaDatumColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, metaDatumDBTypes, false, strmangle.SetComplement(metaDatumPrimaryKeyColumns, metaDatumColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, metaDatumDBTypes, false, strmangle.SetComplement(metaDatumPrimaryKeyColumns, metaDatumColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*MetaDatum{&b, &c} {
		err = a.SetMetaDataIdMetaDatum(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.MetaDataIdMetaDatum != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.MetaDataIdUserMetaData[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if !queries.Equal(a.MetaDataId, x.ID) {
			t.Error("foreign key was wrong value", a.MetaDataId)
		}

		if exists, err := UserMetaDatumExists(ctx, tx, a.UserId, a.MetaDataId); err != nil {
			t.Fatal(err)
		} else if !exists {
			t.Error("want 'a' to exist")
		}

	}
}

func testUserMetaDatumToOneRemoveOpMetaDatumUsingMetaDataIdMetaDatum(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a UserMetaDatum
	var b MetaDatum

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, userMetaDatumDBTypes, false, strmangle.SetComplement(userMetaDatumPrimaryKeyColumns, userMetaDatumColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, metaDatumDBTypes, false, strmangle.SetComplement(metaDatumPrimaryKeyColumns, metaDatumColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = a.SetMetaDataIdMetaDatum(ctx, tx, true, &b); err != nil {
		t.Fatal(err)
	}

	if err = a.RemoveMetaDataIdMetaDatum(ctx, tx, &b); err != nil {
		t.Error("failed to remove relationship")
	}

	count, err := a.MetaDataIdMetaDatum().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 0 {
		t.Error("want no relationships remaining")
	}

	if a.R.MetaDataIdMetaDatum != nil {
		t.Error("R struct entry should be nil")
	}

	if !queries.IsValuerNil(a.MetaDataId) {
		t.Error("foreign key value should be nil")
	}

	if len(b.R.MetaDataIdUserMetaData) != 0 {
		t.Error("failed to remove a from b's relationships")
	}
}

func testUserMetaDatumToOneSetOpUserUsingUserIdUser(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a UserMetaDatum
	var b, c User

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, userMetaDatumDBTypes, false, strmangle.SetComplement(userMetaDatumPrimaryKeyColumns, userMetaDatumColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*User{&b, &c} {
		err = a.SetUserIdUser(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.UserIdUser != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.UserIdUserMetaData[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if !queries.Equal(a.UserId, x.ID) {
			t.Error("foreign key was wrong value", a.UserId)
		}

		if exists, err := UserMetaDatumExists(ctx, tx, a.UserId, a.MetaDataId); err != nil {
			t.Fatal(err)
		} else if !exists {
			t.Error("want 'a' to exist")
		}

	}
}

func testUserMetaDatumToOneRemoveOpUserUsingUserIdUser(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a UserMetaDatum
	var b User

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, userMetaDatumDBTypes, false, strmangle.SetComplement(userMetaDatumPrimaryKeyColumns, userMetaDatumColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = a.SetUserIdUser(ctx, tx, true, &b); err != nil {
		t.Fatal(err)
	}

	if err = a.RemoveUserIdUser(ctx, tx, &b); err != nil {
		t.Error("failed to remove relationship")
	}

	count, err := a.UserIdUser().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 0 {
		t.Error("want no relationships remaining")
	}

	if a.R.UserIdUser != nil {
		t.Error("R struct entry should be nil")
	}

	if !queries.IsValuerNil(a.UserId) {
		t.Error("foreign key value should be nil")
	}

	if len(b.R.UserIdUserMetaData) != 0 {
		t.Error("failed to remove a from b's relationships")
	}
}

func testUserMetaDataReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserMetaDatum{}
	if err = randomize.Struct(seed, o, userMetaDatumDBTypes, true, userMetaDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserMetaDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testUserMetaDataReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserMetaDatum{}
	if err = randomize.Struct(seed, o, userMetaDatumDBTypes, true, userMetaDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserMetaDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := UserMetaDatumSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testUserMetaDataSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserMetaDatum{}
	if err = randomize.Struct(seed, o, userMetaDatumDBTypes, true, userMetaDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserMetaDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := UserMetaData().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	userMetaDatumDBTypes = map[string]string{`UserId`: `INTEGER`, `MetaDataId`: `INTEGER`, `IsWatched`: `BOOLEAN`}
	_                    = bytes.MinRead
)

func testUserMetaDataUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(userMetaDatumPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(userMetaDatumAllColumns) == len(userMetaDatumPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &UserMetaDatum{}
	if err = randomize.Struct(seed, o, userMetaDatumDBTypes, true, userMetaDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserMetaDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := UserMetaData().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, userMetaDatumDBTypes, true, userMetaDatumPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize UserMetaDatum struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testUserMetaDataSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(userMetaDatumAllColumns) == len(userMetaDatumPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &UserMetaDatum{}
	if err = randomize.Struct(seed, o, userMetaDatumDBTypes, true, userMetaDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserMetaDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := UserMetaData().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, userMetaDatumDBTypes, true, userMetaDatumPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize UserMetaDatum struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(userMetaDatumAllColumns, userMetaDatumPrimaryKeyColumns) {
		fields = userMetaDatumAllColumns
	} else {
		fields = strmangle.SetComplement(
			userMetaDatumAllColumns,
			userMetaDatumPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := UserMetaDatumSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testUserMetaDataUpsert(t *testing.T) {
	t.Parallel()
	if len(userMetaDatumAllColumns) == len(userMetaDatumPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := UserMetaDatum{}
	if err = randomize.Struct(seed, &o, userMetaDatumDBTypes, true); err != nil {
		t.Errorf("Unable to randomize UserMetaDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert UserMetaDatum: %s", err)
	}

	count, err := UserMetaData().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, userMetaDatumDBTypes, false, userMetaDatumPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize UserMetaDatum struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert UserMetaDatum: %s", err)
	}

	count, err = UserMetaData().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
